instance:
  id: 0

grpc:
  server:
    port: 8082
server:
  port: 8085

storage:
  master:
    name: "oqsengine"
    query:
      worker: 3 # default cpu core.
      timeout: 3000 # default 3 second
    shard:
      size: 1
  index:
    name: "oqsengine"