instance:
  # static | statefulset 前者读取配置文件,后者使用 k8s statefulset 生成的 hostname.
  type: static
  id: 0

grpc:
  server:
    port: 8081
server:
  port: 8086

logging:
  level:
    root: debug

transaction:
  timeoutms: 3000

threadPool:
  # 0 or not exist use cpu core + 1
  size: 0

storage:
  master:
    name: "oqsbigentity"
    query:
      # default 3 second
      timeout: 3000
    shard:
      table:
        enabled: true
        size: 1
  index:
    # Do not use concatenation symbols such as "_","-". This will cause the execution to fail.
    name: "oqsindex"

management:
  health:
    redis:
      enabled: false
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
