instance:
  # static | statefulset 前者读取配置文件,后者使用 k8s statefulset 生成的 hostname.
  type: static
  id: 0

grpc:
  server:
    port: 8090
server:
  port: 8086

logging:
  level:
    root: info
    io:
      lettuce: info
    com.xforceplus.ultraman.oqsengine.changelog: debug

transaction:
  timeoutMs: 3000

threadPool:
  io:
    # 服务响应线程池.
    worker: 0
    queue: 1000
  task:
    # 后端任务,或者IO线程池中放入的任务执行线程池.
    worker: 0
    queue: 1000

maxVisibleNumber: 10000

ignoreCDCStatusCheck: false
sync:
  allowMaxLiveTimeMs: 3000
  allowMaxUnSyncCommitIdSize: 100

storage:
  tokenizer:
    segmentation:
      lexicon:
        # 字典URL
        url: "-"
  debug:
    showsql: true
  timeoutMs:
    query: 3000
  kv:
    name: "kv"
  master:
    name: "oqsbigentity"
    shard:
      table:
        enabled: false
        size: 1
  index:
    search:
      name: "oqsindex"
      maxQueryTimeMs: 0
      maxBatchSize: 50
    write:
      name: "oqsindex"
      shard:
        enabled: false
        size: 3
  devOps:
    cdc:
      errors:
        name: "cdcerrors"
    maxQueryTimeMs: 3000
    task:
      split: 10
      max:
        queue:
          size: 2000
      execution:
        timeout: 300000
      cache:
        expire: 30
        maxsize: 500
      page:
        size: 1000

redis:
  # 单机 redis://[password@]host[:port][/databaseNumber][?[timeout=timeout[d|h|m|s|ms|us|ns]]
  # 单机SSL rediss://[password@]host[:port][/databaseNumber][?[timeout=timeout[d|h|m|s|ms|us|ns]]
  # 哨兵: redis-sentinel://[password@]host[:port][,host2[:port2]][/databaseNumber][?[timeout=timeout[d|h|m|s|ms|us|ns]]#sentinelMasterId
  # 时间单位
  # d 天
  # h 小时
  # m 分钟
  # s 秒钟
  # ms 毫秒
  # us 微秒
  # ns 纳秒
  #uri: "redis://q1w2e3r4@127.0.0.1:6379"
  uri: "redis://127.0.0.1:6379"
  maxReqQueue: 10000

management:
  health:
    redis:
      enabled: false
    db:
      enabled: false
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true

cdc:
  connect:
    type: single
    host: 127.0.0.1
    port: 11111
    destination: oqsengine
    username: root
    password: root
    subscribeFilter: .*\.oqsbigentity.*
    batchSize: 2048
  consumer:
    checkCommitReady: true
    skipCommitId: -1

meta:
  grpc:
    # client 启动客户端、server 启动服务端、offline 离线模式、mock
    type: client
    host: ultraman.xforcecloud.com
    #    host: 120.55.249.44
    #host: 169.254.106.127
    #    host: localhost
    #    port: 8081
    #    port: 23111
    port: 23120
    seconds:
      heartbeatTimeout: 30
      delaytaskTimeout: 30
      keepAliveDuration: 5
      monitorDuration: 1
      reconnectDuration: 5
  load:
    path: "-"

discover:
  sdk:
    enable: false
    connection:
      host: ultraman.xforcecloud.com
      port: 8916
    time:
      heartbeat:
        expired: 60000
        duration: 5000
    agent:
      serviceName: oqs-engine
      serviceGroup: oqs-engine-group
      serviceId: ${discover.sdk.agent.serviceGroup}-${instance.id}
    threadPool:
      task: 5
      queue: 100

changelog:
  enabled: false
  queue: local

metadata:
  enhanced: false