instance:
  # static | statefulset 前者读取配置文件,后者使用 k8s statefulset 生成的 hostname.
  type: static
  id: 0

grpc:
  server:
    port: 8081
server:
  port: 8086

logging:
  level:
    root: debug

transaction:
  timeoutMs: 3000

threadPool:
  # 0 or not exist use cpu core + 1
  io:
    worker: 0
    queue: 500
  # 0 or not exist use cpu core + 1
  call:
    worker: 0
    queue: 1000

maxVisibleNumber: 10000

storage:
  timeoutMs:
    query: 3000
  master:
    name: "oqsbigentity"
    shard:
      table:
        enabled: false
        size: 1
  index:
    # Do not use concatenation symbols such as "_","-". This will cause the execution to fail.
    name: "oqsindex"
    # The maximum query time for the index, in milliseconds.
    maxQueryTimeMs: 6000
  undo:
    # simple | redis
    store: "simple"


management:
  health:
    redis:
      enabled: false
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
