instance:
  id: 0

grpc:
  server:
    port: 8082
server:
  port: 8086

logging:
  level:
    root: info

storage:
  master:
    name: "oqsbigentity"
    query:
      # default cpu core.
      worker: 3
      # default 3 second
      timeout: 3000
    shard:
      size: 1
  index:
    # Do not use concatenation symbols such as "_","-". This will cause the execution to fail.
    name: "oqsindex"

management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/"