// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sync.proto

package com.xforceplus.ultraman.oqsengine.meta.common.proto.sync;

/**
 * Protobuf type {@code DomainCondition}
 */
public final class DomainCondition extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DomainCondition)
    DomainConditionOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use DomainCondition.newBuilder() to construct.
    private DomainCondition(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private DomainCondition() {
        entityId_ = 0L;
        entityCode_ = "";
        profile_ = "";
        entityFieldId_ = 0L;
        entityFieldCode_ = "";
        fieldType_ = 0;
        operator_ = 0;
        values_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private DomainCondition(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                            input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {

                        entityId_ = input.readInt64();
                        break;
                    }
                    case 18: {
                        java.lang.String s = input.readStringRequireUtf8();

                        entityCode_ = s;
                        break;
                    }
                    case 26: {
                        java.lang.String s = input.readStringRequireUtf8();

                        profile_ = s;
                        break;
                    }
                    case 32: {

                        entityFieldId_ = input.readInt64();
                        break;
                    }
                    case 42: {
                        java.lang.String s = input.readStringRequireUtf8();

                        entityFieldCode_ = s;
                        break;
                    }
                    case 48: {
                        int rawValue = input.readEnum();

                        fieldType_ = rawValue;
                        break;
                    }
                    case 56: {
                        int rawValue = input.readEnum();

                        operator_ = rawValue;
                        break;
                    }
                    case 66: {
                        java.lang.String s = input.readStringRequireUtf8();

                        values_ = s;
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityClassSyncProto.internal_static_DomainCondition_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityClassSyncProto.internal_static_DomainCondition_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.class,
                com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.Builder.class);
    }

    /**
     * Protobuf enum {@code DomainCondition.FieldType}
     */
    public enum FieldType
        implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>UNKNOWN = 0;</code>
         */
        UNKNOWN(0),
        /**
         * <code>BOOLEAN = 1;</code>
         */
        BOOLEAN(1),
        /**
         * <code>ENUM = 2;</code>
         */
        ENUM(2),
        /**
         * <code>DATETIME = 3;</code>
         */
        DATETIME(3),
        /**
         * <code>LONG = 4;</code>
         */
        LONG(4),
        /**
         * <code>STRING = 5;</code>
         */
        STRING(5),
        /**
         * <code>STRINGS = 6;</code>
         */
        STRINGS(6),
        /**
         * <code>DECIMAL = 7;</code>
         */
        DECIMAL(7),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>UNKNOWN = 0;</code>
         */
        public static final int UNKNOWN_VALUE = 0;
        /**
         * <code>BOOLEAN = 1;</code>
         */
        public static final int BOOLEAN_VALUE = 1;
        /**
         * <code>ENUM = 2;</code>
         */
        public static final int ENUM_VALUE = 2;
        /**
         * <code>DATETIME = 3;</code>
         */
        public static final int DATETIME_VALUE = 3;
        /**
         * <code>LONG = 4;</code>
         */
        public static final int LONG_VALUE = 4;
        /**
         * <code>STRING = 5;</code>
         */
        public static final int STRING_VALUE = 5;
        /**
         * <code>STRINGS = 6;</code>
         */
        public static final int STRINGS_VALUE = 6;
        /**
         * <code>DECIMAL = 7;</code>
         */
        public static final int DECIMAL_VALUE = 7;


        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalArgumentException(
                    "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static FieldType valueOf(int value) {
            return forNumber(value);
        }

        public static FieldType forNumber(int value) {
            switch (value) {
                case 0:
                    return UNKNOWN;
                case 1:
                    return BOOLEAN;
                case 2:
                    return ENUM;
                case 3:
                    return DATETIME;
                case 4:
                    return LONG;
                case 5:
                    return STRING;
                case 6:
                    return STRINGS;
                case 7:
                    return DECIMAL;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<FieldType>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static final com.google.protobuf.Internal.EnumLiteMap<
            FieldType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<FieldType>() {
                public FieldType findValueByNumber(int number) {
                    return FieldType.forNumber(number);
                }
            };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.getDescriptor()
                .getEnumTypes().get(0);
        }

        private static final FieldType[] VALUES = values();

        public static FieldType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                    "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private FieldType(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:DomainCondition.FieldType)
    }

    /**
     * Protobuf enum {@code DomainCondition.Operator}
     */
    public enum Operator
        implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>LIKE = 0;</code>
         */
        LIKE(0),
        /**
         * <code>EQUALS = 1;</code>
         */
        EQUALS(1),
        /**
         * <code>NOT_EQUALS = 2;</code>
         */
        NOT_EQUALS(2),
        /**
         * <code>GREATER_THAN = 3;</code>
         */
        GREATER_THAN(3),
        /**
         * <code>GREATER_THAN_EQUALS = 4;</code>
         */
        GREATER_THAN_EQUALS(4),
        /**
         * <code>LESS_THAN = 5;</code>
         */
        LESS_THAN(5),
        /**
         * <code>LESS_THAN_EQUALS = 6;</code>
         */
        LESS_THAN_EQUALS(6),
        /**
         * <code>MULTIPLE_EQUALS = 7;</code>
         */
        MULTIPLE_EQUALS(7),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>LIKE = 0;</code>
         */
        public static final int LIKE_VALUE = 0;
        /**
         * <code>EQUALS = 1;</code>
         */
        public static final int EQUALS_VALUE = 1;
        /**
         * <code>NOT_EQUALS = 2;</code>
         */
        public static final int NOT_EQUALS_VALUE = 2;
        /**
         * <code>GREATER_THAN = 3;</code>
         */
        public static final int GREATER_THAN_VALUE = 3;
        /**
         * <code>GREATER_THAN_EQUALS = 4;</code>
         */
        public static final int GREATER_THAN_EQUALS_VALUE = 4;
        /**
         * <code>LESS_THAN = 5;</code>
         */
        public static final int LESS_THAN_VALUE = 5;
        /**
         * <code>LESS_THAN_EQUALS = 6;</code>
         */
        public static final int LESS_THAN_EQUALS_VALUE = 6;
        /**
         * <code>MULTIPLE_EQUALS = 7;</code>
         */
        public static final int MULTIPLE_EQUALS_VALUE = 7;


        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalArgumentException(
                    "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static Operator valueOf(int value) {
            return forNumber(value);
        }

        public static Operator forNumber(int value) {
            switch (value) {
                case 0:
                    return LIKE;
                case 1:
                    return EQUALS;
                case 2:
                    return NOT_EQUALS;
                case 3:
                    return GREATER_THAN;
                case 4:
                    return GREATER_THAN_EQUALS;
                case 5:
                    return LESS_THAN;
                case 6:
                    return LESS_THAN_EQUALS;
                case 7:
                    return MULTIPLE_EQUALS;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<Operator>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static final com.google.protobuf.Internal.EnumLiteMap<
            Operator> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Operator>() {
                public Operator findValueByNumber(int number) {
                    return Operator.forNumber(number);
                }
            };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.getDescriptor()
                .getEnumTypes().get(1);
        }

        private static final Operator[] VALUES = values();

        public static Operator valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                    "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private Operator(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:DomainCondition.Operator)
    }

    public static final int ENTITYID_FIELD_NUMBER = 1;
    private long entityId_;

    /**
     * <code>int64 entityId = 1;</code>
     */
    public long getEntityId() {
        return entityId_;
    }

    public static final int ENTITYCODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object entityCode_;

    /**
     * <code>string entityCode = 2;</code>
     */
    public java.lang.String getEntityCode() {
        java.lang.Object ref = entityCode_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            entityCode_ = s;
            return s;
        }
    }

    /**
     * <code>string entityCode = 2;</code>
     */
    public com.google.protobuf.ByteString
    getEntityCodeBytes() {
        java.lang.Object ref = entityCode_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            entityCode_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int PROFILE_FIELD_NUMBER = 3;
    private volatile java.lang.Object profile_;

    /**
     * <code>string profile = 3;</code>
     */
    public java.lang.String getProfile() {
        java.lang.Object ref = profile_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            profile_ = s;
            return s;
        }
    }

    /**
     * <code>string profile = 3;</code>
     */
    public com.google.protobuf.ByteString
    getProfileBytes() {
        java.lang.Object ref = profile_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            profile_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int ENTITYFIELDID_FIELD_NUMBER = 4;
    private long entityFieldId_;

    /**
     * <code>int64 entityFieldId = 4;</code>
     */
    public long getEntityFieldId() {
        return entityFieldId_;
    }

    public static final int ENTITYFIELDCODE_FIELD_NUMBER = 5;
    private volatile java.lang.Object entityFieldCode_;

    /**
     * <code>string entityFieldCode = 5;</code>
     */
    public java.lang.String getEntityFieldCode() {
        java.lang.Object ref = entityFieldCode_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            entityFieldCode_ = s;
            return s;
        }
    }

    /**
     * <code>string entityFieldCode = 5;</code>
     */
    public com.google.protobuf.ByteString
    getEntityFieldCodeBytes() {
        java.lang.Object ref = entityFieldCode_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            entityFieldCode_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int FIELDTYPE_FIELD_NUMBER = 6;
    private int fieldType_;

    /**
     * <code>.DomainCondition.FieldType fieldType = 6;</code>
     */
    public int getFieldTypeValue() {
        return fieldType_;
    }

    /**
     * <code>.DomainCondition.FieldType fieldType = 6;</code>
     */
    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.FieldType getFieldType() {
        com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.FieldType result =
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.FieldType.valueOf(fieldType_);
        return result == null ?
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.FieldType.UNRECOGNIZED : result;
    }

    public static final int OPERATOR_FIELD_NUMBER = 7;
    private int operator_;

    /**
     * <code>.DomainCondition.Operator operator = 7;</code>
     */
    public int getOperatorValue() {
        return operator_;
    }

    /**
     * <code>.DomainCondition.Operator operator = 7;</code>
     */
    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.Operator getOperator() {
        com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.Operator result =
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.Operator.valueOf(operator_);
        return result == null ?
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.Operator.UNRECOGNIZED : result;
    }

    public static final int VALUES_FIELD_NUMBER = 8;
    private volatile java.lang.Object values_;

    /**
     * <code>string values = 8;</code>
     */
    public java.lang.String getValues() {
        java.lang.Object ref = values_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            values_ = s;
            return s;
        }
    }

    /**
     * <code>string values = 8;</code>
     */
    public com.google.protobuf.ByteString
    getValuesBytes() {
        java.lang.Object ref = values_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            values_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) {
            return true;
        }
        if (isInitialized == 0) {
            return false;
        }

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
        if (entityId_ != 0L) {
            output.writeInt64(1, entityId_);
        }
        if (!getEntityCodeBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, entityCode_);
        }
        if (!getProfileBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, profile_);
        }
        if (entityFieldId_ != 0L) {
            output.writeInt64(4, entityFieldId_);
        }
        if (!getEntityFieldCodeBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 5, entityFieldCode_);
        }
        if (fieldType_ !=
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.FieldType.UNKNOWN.getNumber()) {
            output.writeEnum(6, fieldType_);
        }
        if (operator_ !=
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.Operator.LIKE.getNumber()) {
            output.writeEnum(7, operator_);
        }
        if (!getValuesBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 8, values_);
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) {
            return size;
        }

        size = 0;
        if (entityId_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(1, entityId_);
        }
        if (!getEntityCodeBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, entityCode_);
        }
        if (!getProfileBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, profile_);
        }
        if (entityFieldId_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(4, entityFieldId_);
        }
        if (!getEntityFieldCodeBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, entityFieldCode_);
        }
        if (fieldType_ !=
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.FieldType.UNKNOWN.getNumber()) {
            size += com.google.protobuf.CodedOutputStream
                .computeEnumSize(6, fieldType_);
        }
        if (operator_ !=
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.Operator.LIKE.getNumber()) {
            size += com.google.protobuf.CodedOutputStream
                .computeEnumSize(7, operator_);
        }
        if (!getValuesBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, values_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition)) {
            return super.equals(obj);
        }
        com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition other =
            (com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition) obj;

        boolean result = true;
        result = result && (getEntityId()
            == other.getEntityId());
        result = result && getEntityCode()
            .equals(other.getEntityCode());
        result = result && getProfile()
            .equals(other.getProfile());
        result = result && (getEntityFieldId()
            == other.getEntityFieldId());
        result = result && getEntityFieldCode()
            .equals(other.getEntityFieldCode());
        result = result && fieldType_ == other.fieldType_;
        result = result && operator_ == other.operator_;
        result = result && getValues()
            .equals(other.getValues());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ENTITYID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getEntityId());
        hash = (37 * hash) + ENTITYCODE_FIELD_NUMBER;
        hash = (53 * hash) + getEntityCode().hashCode();
        hash = (37 * hash) + PROFILE_FIELD_NUMBER;
        hash = (53 * hash) + getProfile().hashCode();
        hash = (37 * hash) + ENTITYFIELDID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getEntityFieldId());
        hash = (37 * hash) + ENTITYFIELDCODE_FIELD_NUMBER;
        hash = (53 * hash) + getEntityFieldCode().hashCode();
        hash = (37 * hash) + FIELDTYPE_FIELD_NUMBER;
        hash = (53 * hash) + fieldType_;
        hash = (37 * hash) + OPERATOR_FIELD_NUMBER;
        hash = (53 * hash) + operator_;
        hash = (37 * hash) + VALUES_FIELD_NUMBER;
        hash = (53 * hash) + getValues().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition parseFrom(
        java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }

    public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition parseDelimitedFrom(
        java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }

    public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code DomainCondition}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DomainCondition)
        com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainConditionOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityClassSyncProto.internal_static_DomainCondition_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityClassSyncProto.internal_static_DomainCondition_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.class,
                    com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.Builder.class);
        }

        // Construct using com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            entityId_ = 0L;

            entityCode_ = "";

            profile_ = "";

            entityFieldId_ = 0L;

            entityFieldCode_ = "";

            fieldType_ = 0;

            operator_ = 0;

            values_ = "";

            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityClassSyncProto.internal_static_DomainCondition_descriptor;
        }

        public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition getDefaultInstanceForType() {
            return com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.getDefaultInstance();
        }

        public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition build() {
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition buildPartial() {
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition result =
                new com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition(this);
            result.entityId_ = entityId_;
            result.entityCode_ = entityCode_;
            result.profile_ = profile_;
            result.entityFieldId_ = entityFieldId_;
            result.entityFieldCode_ = entityFieldCode_;
            result.fieldType_ = fieldType_;
            result.operator_ = operator_;
            result.values_ = values_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition) {
                return mergeFrom((com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition other) {
            if (other ==
                com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.getDefaultInstance()) {
                return this;
            }
            if (other.getEntityId() != 0L) {
                setEntityId(other.getEntityId());
            }
            if (!other.getEntityCode().isEmpty()) {
                entityCode_ = other.entityCode_;
                onChanged();
            }
            if (!other.getProfile().isEmpty()) {
                profile_ = other.profile_;
                onChanged();
            }
            if (other.getEntityFieldId() != 0L) {
                setEntityFieldId(other.getEntityFieldId());
            }
            if (!other.getEntityFieldCode().isEmpty()) {
                entityFieldCode_ = other.entityFieldCode_;
                onChanged();
            }
            if (other.fieldType_ != 0) {
                setFieldTypeValue(other.getFieldTypeValue());
            }
            if (other.operator_ != 0) {
                setOperatorValue(other.getOperatorValue());
            }
            if (!other.getValues().isEmpty()) {
                values_ = other.values_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage =
                    (com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private long entityId_;

        /**
         * <code>int64 entityId = 1;</code>
         */
        public long getEntityId() {
            return entityId_;
        }

        /**
         * <code>int64 entityId = 1;</code>
         */
        public Builder setEntityId(long value) {

            entityId_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int64 entityId = 1;</code>
         */
        public Builder clearEntityId() {

            entityId_ = 0L;
            onChanged();
            return this;
        }

        private java.lang.Object entityCode_ = "";

        /**
         * <code>string entityCode = 2;</code>
         */
        public java.lang.String getEntityCode() {
            java.lang.Object ref = entityCode_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                entityCode_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string entityCode = 2;</code>
         */
        public com.google.protobuf.ByteString
        getEntityCodeBytes() {
            java.lang.Object ref = entityCode_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                entityCode_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string entityCode = 2;</code>
         */
        public Builder setEntityCode(
            java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            entityCode_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string entityCode = 2;</code>
         */
        public Builder clearEntityCode() {

            entityCode_ = getDefaultInstance().getEntityCode();
            onChanged();
            return this;
        }

        /**
         * <code>string entityCode = 2;</code>
         */
        public Builder setEntityCodeBytes(
            com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            entityCode_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object profile_ = "";

        /**
         * <code>string profile = 3;</code>
         */
        public java.lang.String getProfile() {
            java.lang.Object ref = profile_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                profile_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string profile = 3;</code>
         */
        public com.google.protobuf.ByteString
        getProfileBytes() {
            java.lang.Object ref = profile_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                profile_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string profile = 3;</code>
         */
        public Builder setProfile(
            java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            profile_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string profile = 3;</code>
         */
        public Builder clearProfile() {

            profile_ = getDefaultInstance().getProfile();
            onChanged();
            return this;
        }

        /**
         * <code>string profile = 3;</code>
         */
        public Builder setProfileBytes(
            com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            profile_ = value;
            onChanged();
            return this;
        }

        private long entityFieldId_;

        /**
         * <code>int64 entityFieldId = 4;</code>
         */
        public long getEntityFieldId() {
            return entityFieldId_;
        }

        /**
         * <code>int64 entityFieldId = 4;</code>
         */
        public Builder setEntityFieldId(long value) {

            entityFieldId_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int64 entityFieldId = 4;</code>
         */
        public Builder clearEntityFieldId() {

            entityFieldId_ = 0L;
            onChanged();
            return this;
        }

        private java.lang.Object entityFieldCode_ = "";

        /**
         * <code>string entityFieldCode = 5;</code>
         */
        public java.lang.String getEntityFieldCode() {
            java.lang.Object ref = entityFieldCode_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                entityFieldCode_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string entityFieldCode = 5;</code>
         */
        public com.google.protobuf.ByteString
        getEntityFieldCodeBytes() {
            java.lang.Object ref = entityFieldCode_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                entityFieldCode_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string entityFieldCode = 5;</code>
         */
        public Builder setEntityFieldCode(
            java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            entityFieldCode_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string entityFieldCode = 5;</code>
         */
        public Builder clearEntityFieldCode() {

            entityFieldCode_ = getDefaultInstance().getEntityFieldCode();
            onChanged();
            return this;
        }

        /**
         * <code>string entityFieldCode = 5;</code>
         */
        public Builder setEntityFieldCodeBytes(
            com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            entityFieldCode_ = value;
            onChanged();
            return this;
        }

        private int fieldType_ = 0;

        /**
         * <code>.DomainCondition.FieldType fieldType = 6;</code>
         */
        public int getFieldTypeValue() {
            return fieldType_;
        }

        /**
         * <code>.DomainCondition.FieldType fieldType = 6;</code>
         */
        public Builder setFieldTypeValue(int value) {
            fieldType_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>.DomainCondition.FieldType fieldType = 6;</code>
         */
        public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.FieldType getFieldType() {
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.FieldType result =
                com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.FieldType.valueOf(fieldType_);
            return result == null ?
                com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.FieldType.UNRECOGNIZED :
                result;
        }

        /**
         * <code>.DomainCondition.FieldType fieldType = 6;</code>
         */
        public Builder setFieldType(
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.FieldType value) {
            if (value == null) {
                throw new NullPointerException();
            }

            fieldType_ = value.getNumber();
            onChanged();
            return this;
        }

        /**
         * <code>.DomainCondition.FieldType fieldType = 6;</code>
         */
        public Builder clearFieldType() {

            fieldType_ = 0;
            onChanged();
            return this;
        }

        private int operator_ = 0;

        /**
         * <code>.DomainCondition.Operator operator = 7;</code>
         */
        public int getOperatorValue() {
            return operator_;
        }

        /**
         * <code>.DomainCondition.Operator operator = 7;</code>
         */
        public Builder setOperatorValue(int value) {
            operator_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>.DomainCondition.Operator operator = 7;</code>
         */
        public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.Operator getOperator() {
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.Operator result =
                com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.Operator.valueOf(operator_);
            return result == null ?
                com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.Operator.UNRECOGNIZED : result;
        }

        /**
         * <code>.DomainCondition.Operator operator = 7;</code>
         */
        public Builder setOperator(
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition.Operator value) {
            if (value == null) {
                throw new NullPointerException();
            }

            operator_ = value.getNumber();
            onChanged();
            return this;
        }

        /**
         * <code>.DomainCondition.Operator operator = 7;</code>
         */
        public Builder clearOperator() {

            operator_ = 0;
            onChanged();
            return this;
        }

        private java.lang.Object values_ = "";

        /**
         * <code>string values = 8;</code>
         */
        public java.lang.String getValues() {
            java.lang.Object ref = values_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                values_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string values = 8;</code>
         */
        public com.google.protobuf.ByteString
        getValuesBytes() {
            java.lang.Object ref = values_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                values_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string values = 8;</code>
         */
        public Builder setValues(
            java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            values_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string values = 8;</code>
         */
        public Builder clearValues() {

            values_ = getDefaultInstance().getValues();
            onChanged();
            return this;
        }

        /**
         * <code>string values = 8;</code>
         */
        public Builder setValuesBytes(
            com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            values_ = value;
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:DomainCondition)
    }

    // @@protoc_insertion_point(class_scope:DomainCondition)
    private static final com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition();
    }

    public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DomainCondition>
        PARSER = new com.google.protobuf.AbstractParser<DomainCondition>() {
        public DomainCondition parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new DomainCondition(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<DomainCondition> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DomainCondition> getParserForType() {
        return PARSER;
    }

    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.DomainCondition getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

