// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sync.proto

package com.xforceplus.ultraman.oqsengine.meta.common.proto.sync;

/**
 * Protobuf type {@code EntityFieldInfo}
 */
public  final class EntityFieldInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EntityFieldInfo)
    EntityFieldInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EntityFieldInfo.newBuilder() to construct.
  private EntityFieldInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EntityFieldInfo() {
    id_ = 0L;
    name_ = "";
    cname_ = "";
    fieldType_ = "";
    dictId_ = "";
    defaultValue_ = "";
    calculateType_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EntityFieldInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            cname_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            fieldType_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            dictId_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            defaultValue_ = s;
            break;
          }
          case 58: {
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfig.Builder subBuilder = null;
            if (fieldConfig_ != null) {
              subBuilder = fieldConfig_.toBuilder();
            }
            fieldConfig_ = input.readMessage(com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfig.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(fieldConfig_);
              fieldConfig_ = subBuilder.buildPartial();
            }

            break;
          }
          case 64: {

            calculateType_ = input.readInt32();
            break;
          }
          case 74: {
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.Formula.Builder subBuilder = null;
            if (formula_ != null) {
              subBuilder = formula_.toBuilder();
            }
            formula_ = input.readMessage(com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.Formula.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(formula_);
              formula_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityClassSyncProto.internal_static_EntityFieldInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityClassSyncProto.internal_static_EntityFieldInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo.class, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object cname_;
  /**
   * <code>string cname = 3;</code>
   */
  public java.lang.String getCname() {
    java.lang.Object ref = cname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cname_ = s;
      return s;
    }
  }
  /**
   * <code>string cname = 3;</code>
   */
  public com.google.protobuf.ByteString
      getCnameBytes() {
    java.lang.Object ref = cname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELDTYPE_FIELD_NUMBER = 4;
  private volatile java.lang.Object fieldType_;
  /**
   * <code>string fieldType = 4;</code>
   */
  public java.lang.String getFieldType() {
    java.lang.Object ref = fieldType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fieldType_ = s;
      return s;
    }
  }
  /**
   * <code>string fieldType = 4;</code>
   */
  public com.google.protobuf.ByteString
      getFieldTypeBytes() {
    java.lang.Object ref = fieldType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fieldType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DICTID_FIELD_NUMBER = 5;
  private volatile java.lang.Object dictId_;
  /**
   * <code>string dictId = 5;</code>
   */
  public java.lang.String getDictId() {
    java.lang.Object ref = dictId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dictId_ = s;
      return s;
    }
  }
  /**
   * <code>string dictId = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDictIdBytes() {
    java.lang.Object ref = dictId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dictId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEFAULTVALUE_FIELD_NUMBER = 6;
  private volatile java.lang.Object defaultValue_;
  /**
   * <code>string defaultValue = 6;</code>
   */
  public java.lang.String getDefaultValue() {
    java.lang.Object ref = defaultValue_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      defaultValue_ = s;
      return s;
    }
  }
  /**
   * <code>string defaultValue = 6;</code>
   */
  public com.google.protobuf.ByteString
      getDefaultValueBytes() {
    java.lang.Object ref = defaultValue_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      defaultValue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELDCONFIG_FIELD_NUMBER = 7;
  private com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfig fieldConfig_;
  /**
   * <code>.FieldConfig fieldConfig = 7;</code>
   */
  public boolean hasFieldConfig() {
    return fieldConfig_ != null;
  }
  /**
   * <code>.FieldConfig fieldConfig = 7;</code>
   */
  public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfig getFieldConfig() {
    return fieldConfig_ == null ? com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfig.getDefaultInstance() : fieldConfig_;
  }
  /**
   * <code>.FieldConfig fieldConfig = 7;</code>
   */
  public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfigOrBuilder getFieldConfigOrBuilder() {
    return getFieldConfig();
  }

  public static final int CALCULATETYPE_FIELD_NUMBER = 8;
  private int calculateType_;
  /**
   * <code>int32 calculateType = 8;</code>
   */
  public int getCalculateType() {
    return calculateType_;
  }

  public static final int FORMULA_FIELD_NUMBER = 9;
  private com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.Formula formula_;
  /**
   * <code>.Formula formula = 9;</code>
   */
  public boolean hasFormula() {
    return formula_ != null;
  }
  /**
   * <code>.Formula formula = 9;</code>
   */
  public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.Formula getFormula() {
    return formula_ == null ? com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.Formula.getDefaultInstance() : formula_;
  }
  /**
   * <code>.Formula formula = 9;</code>
   */
  public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FormulaOrBuilder getFormulaOrBuilder() {
    return getFormula();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getCnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cname_);
    }
    if (!getFieldTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fieldType_);
    }
    if (!getDictIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, dictId_);
    }
    if (!getDefaultValueBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, defaultValue_);
    }
    if (fieldConfig_ != null) {
      output.writeMessage(7, getFieldConfig());
    }
    if (calculateType_ != 0) {
      output.writeInt32(8, calculateType_);
    }
    if (formula_ != null) {
      output.writeMessage(9, getFormula());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getCnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cname_);
    }
    if (!getFieldTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fieldType_);
    }
    if (!getDictIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, dictId_);
    }
    if (!getDefaultValueBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, defaultValue_);
    }
    if (fieldConfig_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getFieldConfig());
    }
    if (calculateType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, calculateType_);
    }
    if (formula_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getFormula());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo)) {
      return super.equals(obj);
    }
    com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo other = (com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getName()
        .equals(other.getName());
    result = result && getCname()
        .equals(other.getCname());
    result = result && getFieldType()
        .equals(other.getFieldType());
    result = result && getDictId()
        .equals(other.getDictId());
    result = result && getDefaultValue()
        .equals(other.getDefaultValue());
    result = result && (hasFieldConfig() == other.hasFieldConfig());
    if (hasFieldConfig()) {
      result = result && getFieldConfig()
          .equals(other.getFieldConfig());
    }
    result = result && (getCalculateType()
        == other.getCalculateType());
    result = result && (hasFormula() == other.hasFormula());
    if (hasFormula()) {
      result = result && getFormula()
          .equals(other.getFormula());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + CNAME_FIELD_NUMBER;
    hash = (53 * hash) + getCname().hashCode();
    hash = (37 * hash) + FIELDTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getFieldType().hashCode();
    hash = (37 * hash) + DICTID_FIELD_NUMBER;
    hash = (53 * hash) + getDictId().hashCode();
    hash = (37 * hash) + DEFAULTVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getDefaultValue().hashCode();
    if (hasFieldConfig()) {
      hash = (37 * hash) + FIELDCONFIG_FIELD_NUMBER;
      hash = (53 * hash) + getFieldConfig().hashCode();
    }
    hash = (37 * hash) + CALCULATETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getCalculateType();
    if (hasFormula()) {
      hash = (37 * hash) + FORMULA_FIELD_NUMBER;
      hash = (53 * hash) + getFormula().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code EntityFieldInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EntityFieldInfo)
      com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityClassSyncProto.internal_static_EntityFieldInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityClassSyncProto.internal_static_EntityFieldInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo.class, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo.Builder.class);
    }

    // Construct using com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0L;

      name_ = "";

      cname_ = "";

      fieldType_ = "";

      dictId_ = "";

      defaultValue_ = "";

      if (fieldConfigBuilder_ == null) {
        fieldConfig_ = null;
      } else {
        fieldConfig_ = null;
        fieldConfigBuilder_ = null;
      }
      calculateType_ = 0;

      if (formulaBuilder_ == null) {
        formula_ = null;
      } else {
        formula_ = null;
        formulaBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityClassSyncProto.internal_static_EntityFieldInfo_descriptor;
    }

    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo getDefaultInstanceForType() {
      return com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo.getDefaultInstance();
    }

    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo build() {
      com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo buildPartial() {
      com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo result = new com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo(this);
      result.id_ = id_;
      result.name_ = name_;
      result.cname_ = cname_;
      result.fieldType_ = fieldType_;
      result.dictId_ = dictId_;
      result.defaultValue_ = defaultValue_;
      if (fieldConfigBuilder_ == null) {
        result.fieldConfig_ = fieldConfig_;
      } else {
        result.fieldConfig_ = fieldConfigBuilder_.build();
      }
      result.calculateType_ = calculateType_;
      if (formulaBuilder_ == null) {
        result.formula_ = formula_;
      } else {
        result.formula_ = formulaBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo) {
        return mergeFrom((com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo other) {
      if (other == com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getCname().isEmpty()) {
        cname_ = other.cname_;
        onChanged();
      }
      if (!other.getFieldType().isEmpty()) {
        fieldType_ = other.fieldType_;
        onChanged();
      }
      if (!other.getDictId().isEmpty()) {
        dictId_ = other.dictId_;
        onChanged();
      }
      if (!other.getDefaultValue().isEmpty()) {
        defaultValue_ = other.defaultValue_;
        onChanged();
      }
      if (other.hasFieldConfig()) {
        mergeFieldConfig(other.getFieldConfig());
      }
      if (other.getCalculateType() != 0) {
        setCalculateType(other.getCalculateType());
      }
      if (other.hasFormula()) {
        mergeFormula(other.getFormula());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cname_ = "";
    /**
     * <code>string cname = 3;</code>
     */
    public java.lang.String getCname() {
      java.lang.Object ref = cname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cname = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCnameBytes() {
      java.lang.Object ref = cname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cname = 3;</code>
     */
    public Builder setCname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cname = 3;</code>
     */
    public Builder clearCname() {
      
      cname_ = getDefaultInstance().getCname();
      onChanged();
      return this;
    }
    /**
     * <code>string cname = 3;</code>
     */
    public Builder setCnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cname_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object fieldType_ = "";
    /**
     * <code>string fieldType = 4;</code>
     */
    public java.lang.String getFieldType() {
      java.lang.Object ref = fieldType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fieldType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fieldType = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFieldTypeBytes() {
      java.lang.Object ref = fieldType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fieldType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fieldType = 4;</code>
     */
    public Builder setFieldType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fieldType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fieldType = 4;</code>
     */
    public Builder clearFieldType() {
      
      fieldType_ = getDefaultInstance().getFieldType();
      onChanged();
      return this;
    }
    /**
     * <code>string fieldType = 4;</code>
     */
    public Builder setFieldTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fieldType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dictId_ = "";
    /**
     * <code>string dictId = 5;</code>
     */
    public java.lang.String getDictId() {
      java.lang.Object ref = dictId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dictId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dictId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDictIdBytes() {
      java.lang.Object ref = dictId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dictId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dictId = 5;</code>
     */
    public Builder setDictId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dictId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dictId = 5;</code>
     */
    public Builder clearDictId() {
      
      dictId_ = getDefaultInstance().getDictId();
      onChanged();
      return this;
    }
    /**
     * <code>string dictId = 5;</code>
     */
    public Builder setDictIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dictId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object defaultValue_ = "";
    /**
     * <code>string defaultValue = 6;</code>
     */
    public java.lang.String getDefaultValue() {
      java.lang.Object ref = defaultValue_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        defaultValue_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string defaultValue = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDefaultValueBytes() {
      java.lang.Object ref = defaultValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        defaultValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string defaultValue = 6;</code>
     */
    public Builder setDefaultValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      defaultValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string defaultValue = 6;</code>
     */
    public Builder clearDefaultValue() {
      
      defaultValue_ = getDefaultInstance().getDefaultValue();
      onChanged();
      return this;
    }
    /**
     * <code>string defaultValue = 6;</code>
     */
    public Builder setDefaultValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      defaultValue_ = value;
      onChanged();
      return this;
    }

    private com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfig fieldConfig_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfig, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfig.Builder, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfigOrBuilder> fieldConfigBuilder_;
    /**
     * <code>.FieldConfig fieldConfig = 7;</code>
     */
    public boolean hasFieldConfig() {
      return fieldConfigBuilder_ != null || fieldConfig_ != null;
    }
    /**
     * <code>.FieldConfig fieldConfig = 7;</code>
     */
    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfig getFieldConfig() {
      if (fieldConfigBuilder_ == null) {
        return fieldConfig_ == null ? com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfig.getDefaultInstance() : fieldConfig_;
      } else {
        return fieldConfigBuilder_.getMessage();
      }
    }
    /**
     * <code>.FieldConfig fieldConfig = 7;</code>
     */
    public Builder setFieldConfig(com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfig value) {
      if (fieldConfigBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fieldConfig_ = value;
        onChanged();
      } else {
        fieldConfigBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.FieldConfig fieldConfig = 7;</code>
     */
    public Builder setFieldConfig(
        com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfig.Builder builderForValue) {
      if (fieldConfigBuilder_ == null) {
        fieldConfig_ = builderForValue.build();
        onChanged();
      } else {
        fieldConfigBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.FieldConfig fieldConfig = 7;</code>
     */
    public Builder mergeFieldConfig(com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfig value) {
      if (fieldConfigBuilder_ == null) {
        if (fieldConfig_ != null) {
          fieldConfig_ =
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfig.newBuilder(fieldConfig_).mergeFrom(value).buildPartial();
        } else {
          fieldConfig_ = value;
        }
        onChanged();
      } else {
        fieldConfigBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.FieldConfig fieldConfig = 7;</code>
     */
    public Builder clearFieldConfig() {
      if (fieldConfigBuilder_ == null) {
        fieldConfig_ = null;
        onChanged();
      } else {
        fieldConfig_ = null;
        fieldConfigBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.FieldConfig fieldConfig = 7;</code>
     */
    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfig.Builder getFieldConfigBuilder() {
      
      onChanged();
      return getFieldConfigFieldBuilder().getBuilder();
    }
    /**
     * <code>.FieldConfig fieldConfig = 7;</code>
     */
    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfigOrBuilder getFieldConfigOrBuilder() {
      if (fieldConfigBuilder_ != null) {
        return fieldConfigBuilder_.getMessageOrBuilder();
      } else {
        return fieldConfig_ == null ?
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfig.getDefaultInstance() : fieldConfig_;
      }
    }
    /**
     * <code>.FieldConfig fieldConfig = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfig, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfig.Builder, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfigOrBuilder> 
        getFieldConfigFieldBuilder() {
      if (fieldConfigBuilder_ == null) {
        fieldConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfig, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfig.Builder, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FieldConfigOrBuilder>(
                getFieldConfig(),
                getParentForChildren(),
                isClean());
        fieldConfig_ = null;
      }
      return fieldConfigBuilder_;
    }

    private int calculateType_ ;
    /**
     * <code>int32 calculateType = 8;</code>
     */
    public int getCalculateType() {
      return calculateType_;
    }
    /**
     * <code>int32 calculateType = 8;</code>
     */
    public Builder setCalculateType(int value) {
      
      calculateType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 calculateType = 8;</code>
     */
    public Builder clearCalculateType() {
      
      calculateType_ = 0;
      onChanged();
      return this;
    }

    private com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.Formula formula_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.Formula, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.Formula.Builder, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FormulaOrBuilder> formulaBuilder_;
    /**
     * <code>.Formula formula = 9;</code>
     */
    public boolean hasFormula() {
      return formulaBuilder_ != null || formula_ != null;
    }
    /**
     * <code>.Formula formula = 9;</code>
     */
    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.Formula getFormula() {
      if (formulaBuilder_ == null) {
        return formula_ == null ? com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.Formula.getDefaultInstance() : formula_;
      } else {
        return formulaBuilder_.getMessage();
      }
    }
    /**
     * <code>.Formula formula = 9;</code>
     */
    public Builder setFormula(com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.Formula value) {
      if (formulaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        formula_ = value;
        onChanged();
      } else {
        formulaBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Formula formula = 9;</code>
     */
    public Builder setFormula(
        com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.Formula.Builder builderForValue) {
      if (formulaBuilder_ == null) {
        formula_ = builderForValue.build();
        onChanged();
      } else {
        formulaBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Formula formula = 9;</code>
     */
    public Builder mergeFormula(com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.Formula value) {
      if (formulaBuilder_ == null) {
        if (formula_ != null) {
          formula_ =
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.Formula.newBuilder(formula_).mergeFrom(value).buildPartial();
        } else {
          formula_ = value;
        }
        onChanged();
      } else {
        formulaBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Formula formula = 9;</code>
     */
    public Builder clearFormula() {
      if (formulaBuilder_ == null) {
        formula_ = null;
        onChanged();
      } else {
        formula_ = null;
        formulaBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Formula formula = 9;</code>
     */
    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.Formula.Builder getFormulaBuilder() {
      
      onChanged();
      return getFormulaFieldBuilder().getBuilder();
    }
    /**
     * <code>.Formula formula = 9;</code>
     */
    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FormulaOrBuilder getFormulaOrBuilder() {
      if (formulaBuilder_ != null) {
        return formulaBuilder_.getMessageOrBuilder();
      } else {
        return formula_ == null ?
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.Formula.getDefaultInstance() : formula_;
      }
    }
    /**
     * <code>.Formula formula = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.Formula, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.Formula.Builder, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FormulaOrBuilder> 
        getFormulaFieldBuilder() {
      if (formulaBuilder_ == null) {
        formulaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.Formula, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.Formula.Builder, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.FormulaOrBuilder>(
                getFormula(),
                getParentForChildren(),
                isClean());
        formula_ = null;
      }
      return formulaBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:EntityFieldInfo)
  }

  // @@protoc_insertion_point(class_scope:EntityFieldInfo)
  private static final com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo();
  }

  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EntityFieldInfo>
      PARSER = new com.google.protobuf.AbstractParser<EntityFieldInfo>() {
    public EntityFieldInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EntityFieldInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EntityFieldInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EntityFieldInfo> getParserForType() {
    return PARSER;
  }

  public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

