// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sync.proto

package com.xforceplus.ultraman.oqsengine.meta.common.proto.sync;

public interface FormulaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Formula)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string formula = 1;</code>
   */
  java.lang.String getFormula();
  /**
   * <code>string formula = 1;</code>
   */
  com.google.protobuf.ByteString
      getFormulaBytes();

  /**
   * <code>string validator = 2;</code>
   */
  java.lang.String getValidator();
  /**
   * <code>string validator = 2;</code>
   */
  com.google.protobuf.ByteString
      getValidatorBytes();

  /**
   * <code>string min = 3;</code>
   */
  java.lang.String getMin();
  /**
   * <code>string min = 3;</code>
   */
  com.google.protobuf.ByteString
      getMinBytes();

  /**
   * <code>string max = 4;</code>
   */
  java.lang.String getMax();
  /**
   * <code>string max = 4;</code>
   */
  com.google.protobuf.ByteString
      getMaxBytes();

  /**
   * <code>string condition = 5;</code>
   */
  java.lang.String getCondition();
  /**
   * <code>string condition = 5;</code>
   */
  com.google.protobuf.ByteString
      getConditionBytes();

  /**
   * <code>string emptyValueTransfer = 6;</code>
   */
  java.lang.String getEmptyValueTransfer();
  /**
   * <code>string emptyValueTransfer = 6;</code>
   */
  com.google.protobuf.ByteString
      getEmptyValueTransferBytes();

  /**
   * <code>string patten = 7;</code>
   */
  java.lang.String getPatten();
  /**
   * <code>string patten = 7;</code>
   */
  com.google.protobuf.ByteString
      getPattenBytes();

  /**
   * <code>string model = 8;</code>
   */
  java.lang.String getModel();
  /**
   * <code>string model = 8;</code>
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>int32 step = 9;</code>
   */
  int getStep();

  /**
   * <code>int32 level = 10;</code>
   */
  int getLevel();
}
