// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sync.proto

package com.xforceplus.ultraman.oqsengine.meta.common.proto.sync;

/**
 * Protobuf type {@code ProfileInfo}
 */
public  final class ProfileInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ProfileInfo)
    ProfileInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProfileInfo.newBuilder() to construct.
  private ProfileInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProfileInfo() {
    code_ = "";
    entityFieldInfo_ = java.util.Collections.emptyList();
    relationInfo_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProfileInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            code_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              entityFieldInfo_ = new java.util.ArrayList<com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo>();
              mutable_bitField0_ |= 0x00000002;
            }
            entityFieldInfo_.add(
                input.readMessage(com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo.parser(), extensionRegistry));
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              relationInfo_ = new java.util.ArrayList<com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo>();
              mutable_bitField0_ |= 0x00000004;
            }
            relationInfo_.add(
                input.readMessage(com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        entityFieldInfo_ = java.util.Collections.unmodifiableList(entityFieldInfo_);
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        relationInfo_ = java.util.Collections.unmodifiableList(relationInfo_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityClassSyncProto.internal_static_ProfileInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityClassSyncProto.internal_static_ProfileInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo.class, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo.Builder.class);
  }

  private int bitField0_;
  public static final int CODE_FIELD_NUMBER = 1;
  private volatile java.lang.Object code_;
  /**
   * <code>string code = 1;</code>
   */
  public java.lang.String getCode() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      code_ = s;
      return s;
    }
  }
  /**
   * <code>string code = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCodeBytes() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      code_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENTITYFIELDINFO_FIELD_NUMBER = 2;
  private java.util.List<com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo> entityFieldInfo_;
  /**
   * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
   */
  public java.util.List<com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo> getEntityFieldInfoList() {
    return entityFieldInfo_;
  }
  /**
   * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
   */
  public java.util.List<? extends com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfoOrBuilder> 
      getEntityFieldInfoOrBuilderList() {
    return entityFieldInfo_;
  }
  /**
   * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
   */
  public int getEntityFieldInfoCount() {
    return entityFieldInfo_.size();
  }
  /**
   * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
   */
  public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo getEntityFieldInfo(int index) {
    return entityFieldInfo_.get(index);
  }
  /**
   * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
   */
  public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfoOrBuilder getEntityFieldInfoOrBuilder(
      int index) {
    return entityFieldInfo_.get(index);
  }

  public static final int RELATIONINFO_FIELD_NUMBER = 3;
  private java.util.List<com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo> relationInfo_;
  /**
   * <code>repeated .RelationInfo relationInfo = 3;</code>
   */
  public java.util.List<com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo> getRelationInfoList() {
    return relationInfo_;
  }
  /**
   * <code>repeated .RelationInfo relationInfo = 3;</code>
   */
  public java.util.List<? extends com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfoOrBuilder> 
      getRelationInfoOrBuilderList() {
    return relationInfo_;
  }
  /**
   * <code>repeated .RelationInfo relationInfo = 3;</code>
   */
  public int getRelationInfoCount() {
    return relationInfo_.size();
  }
  /**
   * <code>repeated .RelationInfo relationInfo = 3;</code>
   */
  public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo getRelationInfo(int index) {
    return relationInfo_.get(index);
  }
  /**
   * <code>repeated .RelationInfo relationInfo = 3;</code>
   */
  public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfoOrBuilder getRelationInfoOrBuilder(
      int index) {
    return relationInfo_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, code_);
    }
    for (int i = 0; i < entityFieldInfo_.size(); i++) {
      output.writeMessage(2, entityFieldInfo_.get(i));
    }
    for (int i = 0; i < relationInfo_.size(); i++) {
      output.writeMessage(3, relationInfo_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, code_);
    }
    for (int i = 0; i < entityFieldInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, entityFieldInfo_.get(i));
    }
    for (int i = 0; i < relationInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, relationInfo_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo)) {
      return super.equals(obj);
    }
    com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo other = (com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo) obj;

    boolean result = true;
    result = result && getCode()
        .equals(other.getCode());
    result = result && getEntityFieldInfoList()
        .equals(other.getEntityFieldInfoList());
    result = result && getRelationInfoList()
        .equals(other.getRelationInfoList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode().hashCode();
    if (getEntityFieldInfoCount() > 0) {
      hash = (37 * hash) + ENTITYFIELDINFO_FIELD_NUMBER;
      hash = (53 * hash) + getEntityFieldInfoList().hashCode();
    }
    if (getRelationInfoCount() > 0) {
      hash = (37 * hash) + RELATIONINFO_FIELD_NUMBER;
      hash = (53 * hash) + getRelationInfoList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ProfileInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ProfileInfo)
      com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityClassSyncProto.internal_static_ProfileInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityClassSyncProto.internal_static_ProfileInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo.class, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo.Builder.class);
    }

    // Construct using com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEntityFieldInfoFieldBuilder();
        getRelationInfoFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      code_ = "";

      if (entityFieldInfoBuilder_ == null) {
        entityFieldInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        entityFieldInfoBuilder_.clear();
      }
      if (relationInfoBuilder_ == null) {
        relationInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        relationInfoBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityClassSyncProto.internal_static_ProfileInfo_descriptor;
    }

    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo getDefaultInstanceForType() {
      return com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo.getDefaultInstance();
    }

    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo build() {
      com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo buildPartial() {
      com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo result = new com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.code_ = code_;
      if (entityFieldInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          entityFieldInfo_ = java.util.Collections.unmodifiableList(entityFieldInfo_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.entityFieldInfo_ = entityFieldInfo_;
      } else {
        result.entityFieldInfo_ = entityFieldInfoBuilder_.build();
      }
      if (relationInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          relationInfo_ = java.util.Collections.unmodifiableList(relationInfo_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.relationInfo_ = relationInfo_;
      } else {
        result.relationInfo_ = relationInfoBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo) {
        return mergeFrom((com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo other) {
      if (other == com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo.getDefaultInstance()) return this;
      if (!other.getCode().isEmpty()) {
        code_ = other.code_;
        onChanged();
      }
      if (entityFieldInfoBuilder_ == null) {
        if (!other.entityFieldInfo_.isEmpty()) {
          if (entityFieldInfo_.isEmpty()) {
            entityFieldInfo_ = other.entityFieldInfo_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureEntityFieldInfoIsMutable();
            entityFieldInfo_.addAll(other.entityFieldInfo_);
          }
          onChanged();
        }
      } else {
        if (!other.entityFieldInfo_.isEmpty()) {
          if (entityFieldInfoBuilder_.isEmpty()) {
            entityFieldInfoBuilder_.dispose();
            entityFieldInfoBuilder_ = null;
            entityFieldInfo_ = other.entityFieldInfo_;
            bitField0_ = (bitField0_ & ~0x00000002);
            entityFieldInfoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEntityFieldInfoFieldBuilder() : null;
          } else {
            entityFieldInfoBuilder_.addAllMessages(other.entityFieldInfo_);
          }
        }
      }
      if (relationInfoBuilder_ == null) {
        if (!other.relationInfo_.isEmpty()) {
          if (relationInfo_.isEmpty()) {
            relationInfo_ = other.relationInfo_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureRelationInfoIsMutable();
            relationInfo_.addAll(other.relationInfo_);
          }
          onChanged();
        }
      } else {
        if (!other.relationInfo_.isEmpty()) {
          if (relationInfoBuilder_.isEmpty()) {
            relationInfoBuilder_.dispose();
            relationInfoBuilder_ = null;
            relationInfo_ = other.relationInfo_;
            bitField0_ = (bitField0_ & ~0x00000004);
            relationInfoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRelationInfoFieldBuilder() : null;
          } else {
            relationInfoBuilder_.addAllMessages(other.relationInfo_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object code_ = "";
    /**
     * <code>string code = 1;</code>
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string code = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string code = 1;</code>
     */
    public Builder setCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string code = 1;</code>
     */
    public Builder clearCode() {
      
      code_ = getDefaultInstance().getCode();
      onChanged();
      return this;
    }
    /**
     * <code>string code = 1;</code>
     */
    public Builder setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      code_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo> entityFieldInfo_ =
      java.util.Collections.emptyList();
    private void ensureEntityFieldInfoIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        entityFieldInfo_ = new java.util.ArrayList<com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo>(entityFieldInfo_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo.Builder, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfoOrBuilder> entityFieldInfoBuilder_;

    /**
     * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
     */
    public java.util.List<com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo> getEntityFieldInfoList() {
      if (entityFieldInfoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(entityFieldInfo_);
      } else {
        return entityFieldInfoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
     */
    public int getEntityFieldInfoCount() {
      if (entityFieldInfoBuilder_ == null) {
        return entityFieldInfo_.size();
      } else {
        return entityFieldInfoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
     */
    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo getEntityFieldInfo(int index) {
      if (entityFieldInfoBuilder_ == null) {
        return entityFieldInfo_.get(index);
      } else {
        return entityFieldInfoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
     */
    public Builder setEntityFieldInfo(
        int index, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo value) {
      if (entityFieldInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntityFieldInfoIsMutable();
        entityFieldInfo_.set(index, value);
        onChanged();
      } else {
        entityFieldInfoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
     */
    public Builder setEntityFieldInfo(
        int index, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo.Builder builderForValue) {
      if (entityFieldInfoBuilder_ == null) {
        ensureEntityFieldInfoIsMutable();
        entityFieldInfo_.set(index, builderForValue.build());
        onChanged();
      } else {
        entityFieldInfoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
     */
    public Builder addEntityFieldInfo(com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo value) {
      if (entityFieldInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntityFieldInfoIsMutable();
        entityFieldInfo_.add(value);
        onChanged();
      } else {
        entityFieldInfoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
     */
    public Builder addEntityFieldInfo(
        int index, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo value) {
      if (entityFieldInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntityFieldInfoIsMutable();
        entityFieldInfo_.add(index, value);
        onChanged();
      } else {
        entityFieldInfoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
     */
    public Builder addEntityFieldInfo(
        com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo.Builder builderForValue) {
      if (entityFieldInfoBuilder_ == null) {
        ensureEntityFieldInfoIsMutable();
        entityFieldInfo_.add(builderForValue.build());
        onChanged();
      } else {
        entityFieldInfoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
     */
    public Builder addEntityFieldInfo(
        int index, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo.Builder builderForValue) {
      if (entityFieldInfoBuilder_ == null) {
        ensureEntityFieldInfoIsMutable();
        entityFieldInfo_.add(index, builderForValue.build());
        onChanged();
      } else {
        entityFieldInfoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
     */
    public Builder addAllEntityFieldInfo(
        java.lang.Iterable<? extends com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo> values) {
      if (entityFieldInfoBuilder_ == null) {
        ensureEntityFieldInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, entityFieldInfo_);
        onChanged();
      } else {
        entityFieldInfoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
     */
    public Builder clearEntityFieldInfo() {
      if (entityFieldInfoBuilder_ == null) {
        entityFieldInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        entityFieldInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
     */
    public Builder removeEntityFieldInfo(int index) {
      if (entityFieldInfoBuilder_ == null) {
        ensureEntityFieldInfoIsMutable();
        entityFieldInfo_.remove(index);
        onChanged();
      } else {
        entityFieldInfoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
     */
    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo.Builder getEntityFieldInfoBuilder(
        int index) {
      return getEntityFieldInfoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
     */
    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfoOrBuilder getEntityFieldInfoOrBuilder(
        int index) {
      if (entityFieldInfoBuilder_ == null) {
        return entityFieldInfo_.get(index);  } else {
        return entityFieldInfoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
     */
    public java.util.List<? extends com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfoOrBuilder> 
         getEntityFieldInfoOrBuilderList() {
      if (entityFieldInfoBuilder_ != null) {
        return entityFieldInfoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(entityFieldInfo_);
      }
    }
    /**
     * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
     */
    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo.Builder addEntityFieldInfoBuilder() {
      return getEntityFieldInfoFieldBuilder().addBuilder(
          com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
     */
    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo.Builder addEntityFieldInfoBuilder(
        int index) {
      return getEntityFieldInfoFieldBuilder().addBuilder(
          index, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .EntityFieldInfo entityFieldInfo = 2;</code>
     */
    public java.util.List<com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo.Builder> 
         getEntityFieldInfoBuilderList() {
      return getEntityFieldInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo.Builder, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfoOrBuilder> 
        getEntityFieldInfoFieldBuilder() {
      if (entityFieldInfoBuilder_ == null) {
        entityFieldInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfo.Builder, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.EntityFieldInfoOrBuilder>(
                entityFieldInfo_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        entityFieldInfo_ = null;
      }
      return entityFieldInfoBuilder_;
    }

    private java.util.List<com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo> relationInfo_ =
      java.util.Collections.emptyList();
    private void ensureRelationInfoIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        relationInfo_ = new java.util.ArrayList<com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo>(relationInfo_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo.Builder, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfoOrBuilder> relationInfoBuilder_;

    /**
     * <code>repeated .RelationInfo relationInfo = 3;</code>
     */
    public java.util.List<com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo> getRelationInfoList() {
      if (relationInfoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(relationInfo_);
      } else {
        return relationInfoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .RelationInfo relationInfo = 3;</code>
     */
    public int getRelationInfoCount() {
      if (relationInfoBuilder_ == null) {
        return relationInfo_.size();
      } else {
        return relationInfoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .RelationInfo relationInfo = 3;</code>
     */
    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo getRelationInfo(int index) {
      if (relationInfoBuilder_ == null) {
        return relationInfo_.get(index);
      } else {
        return relationInfoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .RelationInfo relationInfo = 3;</code>
     */
    public Builder setRelationInfo(
        int index, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo value) {
      if (relationInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRelationInfoIsMutable();
        relationInfo_.set(index, value);
        onChanged();
      } else {
        relationInfoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .RelationInfo relationInfo = 3;</code>
     */
    public Builder setRelationInfo(
        int index, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo.Builder builderForValue) {
      if (relationInfoBuilder_ == null) {
        ensureRelationInfoIsMutable();
        relationInfo_.set(index, builderForValue.build());
        onChanged();
      } else {
        relationInfoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .RelationInfo relationInfo = 3;</code>
     */
    public Builder addRelationInfo(com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo value) {
      if (relationInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRelationInfoIsMutable();
        relationInfo_.add(value);
        onChanged();
      } else {
        relationInfoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .RelationInfo relationInfo = 3;</code>
     */
    public Builder addRelationInfo(
        int index, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo value) {
      if (relationInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRelationInfoIsMutable();
        relationInfo_.add(index, value);
        onChanged();
      } else {
        relationInfoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .RelationInfo relationInfo = 3;</code>
     */
    public Builder addRelationInfo(
        com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo.Builder builderForValue) {
      if (relationInfoBuilder_ == null) {
        ensureRelationInfoIsMutable();
        relationInfo_.add(builderForValue.build());
        onChanged();
      } else {
        relationInfoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .RelationInfo relationInfo = 3;</code>
     */
    public Builder addRelationInfo(
        int index, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo.Builder builderForValue) {
      if (relationInfoBuilder_ == null) {
        ensureRelationInfoIsMutable();
        relationInfo_.add(index, builderForValue.build());
        onChanged();
      } else {
        relationInfoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .RelationInfo relationInfo = 3;</code>
     */
    public Builder addAllRelationInfo(
        java.lang.Iterable<? extends com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo> values) {
      if (relationInfoBuilder_ == null) {
        ensureRelationInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, relationInfo_);
        onChanged();
      } else {
        relationInfoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .RelationInfo relationInfo = 3;</code>
     */
    public Builder clearRelationInfo() {
      if (relationInfoBuilder_ == null) {
        relationInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        relationInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .RelationInfo relationInfo = 3;</code>
     */
    public Builder removeRelationInfo(int index) {
      if (relationInfoBuilder_ == null) {
        ensureRelationInfoIsMutable();
        relationInfo_.remove(index);
        onChanged();
      } else {
        relationInfoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .RelationInfo relationInfo = 3;</code>
     */
    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo.Builder getRelationInfoBuilder(
        int index) {
      return getRelationInfoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .RelationInfo relationInfo = 3;</code>
     */
    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfoOrBuilder getRelationInfoOrBuilder(
        int index) {
      if (relationInfoBuilder_ == null) {
        return relationInfo_.get(index);  } else {
        return relationInfoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .RelationInfo relationInfo = 3;</code>
     */
    public java.util.List<? extends com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfoOrBuilder> 
         getRelationInfoOrBuilderList() {
      if (relationInfoBuilder_ != null) {
        return relationInfoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(relationInfo_);
      }
    }
    /**
     * <code>repeated .RelationInfo relationInfo = 3;</code>
     */
    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo.Builder addRelationInfoBuilder() {
      return getRelationInfoFieldBuilder().addBuilder(
          com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .RelationInfo relationInfo = 3;</code>
     */
    public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo.Builder addRelationInfoBuilder(
        int index) {
      return getRelationInfoFieldBuilder().addBuilder(
          index, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .RelationInfo relationInfo = 3;</code>
     */
    public java.util.List<com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo.Builder> 
         getRelationInfoBuilderList() {
      return getRelationInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo.Builder, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfoOrBuilder> 
        getRelationInfoFieldBuilder() {
      if (relationInfoBuilder_ == null) {
        relationInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfo.Builder, com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.RelationInfoOrBuilder>(
                relationInfo_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        relationInfo_ = null;
      }
      return relationInfoBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ProfileInfo)
  }

  // @@protoc_insertion_point(class_scope:ProfileInfo)
  private static final com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo();
  }

  public static com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProfileInfo>
      PARSER = new com.google.protobuf.AbstractParser<ProfileInfo>() {
    public ProfileInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProfileInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProfileInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProfileInfo> getParserForType() {
    return PARSER;
  }

  public com.xforceplus.ultraman.oqsengine.meta.common.proto.sync.ProfileInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

