image: registry.cn-hangzhou.aliyuncs.com/xforceplus/cibase:std-cibase-0.0.1

stages:
  - mvn-package
  - tag-mvn-deploy
  - docker-build

maven-build:
  stage: mvn-package
  coverage: '/Total.*?([0-9]{1,3})%/'
  script:
    - update_pom_version
    - mvn clean install -s -Dmaven.test.skip=true ./.mvn/wrapper/settings.xml
    - cat target/site/jacoco/index.html
    - mkdir -p /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    - cp ./target/xplat-meta-oqsengine.jar /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/app.jar
  except:
    - tags

tag-mvn-deploy:
  stage: tag-mvn-deploy
  coverage: '/Total.*?([0-9]{1,3})%/'
  script:
    - update_pom_version
    - mvn clean deploy -s ./.mvn/wrapper/settings.xml -Dmaven.test.skip=true
    - mkdir -p /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    - cp ./target/xplat-meta-oqsengine.jar /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/app.jar
  only:
    - tags

docker-build:
  stage: docker-build
  script:
    - docker_build
    - chart_build
  except:
    - /^.*-sdk$/

.auto_devops: &auto_devops |
  http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 10 -w %{http_code} "${CHOERODON_URL}/devops/ci?token=${Token}&type=microservice"`
  if [ "$http_status_code" != "200" ]; then
    cat .auto_devops.sh
    exit 1
  fi
  source .auto_devops.sh
  function docker_build(){
      cp /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/app.jar ${1:-"docker"}/app.jar || true
      docker build --pull -t ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG} ${1:-"docker"}
      docker login ${DOCKER_REGISTRY} -u ${DOCKER_USER} -p ${DOCKER_PWD}
      docker push ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}
      rm -rf /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
  }

.mvnwfix: &mvnwfix |
  export MAVEN_CONFIG=''

before_script:
  - *mvnwfix
  - *auto_devops
