image: registry.cn-hangzhou.aliyuncs.com/xforceplus/cibase:std-cibase-0.0.1


stages:
  - mvn-package
  - tag-mvn-deploy
  - docker-build

maven-build:
  stage: mvn-package
  coverage: '/Total.*?([0-9]{1,3})%/'
  script:
    - update_pom_version
    - mvn clean install -U -s ./.mvn/wrapper/settings.xml -Dmaven.test.skip=true
    - cat target/site/jacoco/index.html
    - mkdir -p /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    - cp ./target/xplat-meta-oqsengine.jar /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/app.jar
  except:
    - tags
    - master
  tags:
    - oqs

tag-mvn-deploy:
  stage: tag-mvn-deploy
  coverage: '/Total.*?([0-9]{1,3})%/'
  script:
    - update_pom_version
    - mvn clean deploy -U -s ./.mvn/wrapper/settings.xml -Dmaven.test.skip=true
    - mkdir -p /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    - cp ./target/xplat-meta-oqsengine.jar /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/app.jar
  only:
    - tags
    - master
  tags:
    - oqs

docker-build:
  stage: docker-build
  script:
    - docker_build
    - chart_build
  except:
    - /^.*-sdk$/
    - master
    - develop
  tags:
    - oqs

.auto_devops: &auto_devops |
  http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 10 -w %{http_code} "http://gitlab4.0.xforceplus.com/common/gitlabci4/raw/devops-gitlabci/ci/.auto_devops"`
  if [ "$http_status_code" != "200" ]; then
    echo "Check that ${CHOERODON_URL} is not 200."
    cat .auto_devops.sh
    exit 1
  fi
  source .auto_devops.sh
  function docker_build(){
      cp /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/app.jar ${1:-"docker"}/app.jar || true
      docker build --pull -t ${DOCKER_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG} ${1:-"docker"}
      docker tag ${DOCKER_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG} ${DOCKER_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:latest
      docker login ${DOCKER_REGISTRY} -u ${DOCKER_USER} -p ${DOCKER_PWD}
      docker push ${DOCKER_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
      rm -rf /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
  }

.mvnwfix: &mvnwfix |
  export MAVEN_CONFIG=''

before_script:
  - *mvnwfix
  - *auto_devops
