apiVersion: v1
kind: Service
metadata:
  name: {{ template "oqsengine.fullname" . }}-http
  labels:
    app: {{ template "oqsengine.name" . }}
    chart: {{ template "oqsengine.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.http }}
      targetPort: http-metrics
      protocol: TCP
      name: http
  selector:
    app: {{ template "oqsengine.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "oqsengine.fullname" . }}-grpc
  labels:
    app: {{ template "oqsengine.name" . }}
    chart: {{ template "oqsengine.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: {{ template "oqsengine.name" . }}
    release: {{ .Release.Name }}