apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "oqsengine.fullname" . }}
  labels:
    app: {{ template "oqsengine.name" . }}
    chart: {{ template "oqsengine.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: ""
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "oqsengine.name" . }}
      release: {{ .Release.Name }}
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: {{ template "oqsengine.name" . }}
        release: {{ .Release.Name }}
      {{- with .Values.annotations }}
      annotations:
{{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ template "image.tag" . }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        lifecycle:
          preStop:
            exec:
              command: [ "/bin/sh","-c","curl","-X","POST","http://127.0.0.1:8086/actuator/shutdown" ]
        env:
        {{- range .Values.environment }}
        {{- range $k,$v := . }}
        - name: {{ $k }}
          value: {{ $v |quote }}
        {{- end }}
        {{- end }}
        command: [ "java" ]
        args:
          {{- if .Values.storage.debug.remote.enabled }}
          - -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5050
          {{- end }}
          - -jar
          {{- range .Values.jvm }}
          - {{ . }}
          {{- end }}
          {{- if .Values.jmx.enabled }}
          - -Dcom.sun.management.jmxremote
          - -Dcom.sun.management.jmxremote.ssl=false
          - -Dcom.sun.management.jmxremote.authenticate=false
          - -Dcom.sun.management.jmxremote.port={{ .Values.jmx.port | default "1099" }}
          - -Dcom.sun.management.jmxremote.rmi.port={{ .Values.jmx.port | default "1099" }}
          - -Djava.rmi.server.hostname={{ .Values.jmx.hostname | default "127.0.0.1" }}
          {{- end }}
          - -Dds=/xplat/oqsengine-ds.conf
          - -Duser.timezone=GMT+8
          - /xplat/xplat-meta-oqsengine.jar
          - --spring.config.location=/xplat/application.yml
        ports:
          {{- if .Values.storage.debug.remote.enabled }}
        - name: debug
          containerPort: 5050
          protocol: TCP
          {{- end }}
        - name: http-metrics
          containerPort: 8086
          protocol: TCP
        - name: grpc
          containerPort: 8081
          protocol: TCP
          {{- if .Values.jmx.enabled }}
        - name: jmx
          containerPort: {{ .Values.jmx.port | default "1099" }}
          protocol: TCP
          {{- end }}
        volumeMounts:
        - mountPath: /xplat/application.yml
          name: config
          subPath: application.yml
        - mountPath: /xplat/oqsengine-ds.conf
          name: config
          subPath: oqsengine-ds.conf
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /actuator/prometheus
            port: 8086
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 3
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /actuator/health
            port: 8086
          initialDelaySeconds: 30
          periodSeconds: 6
          failureThreshold: 3
          timeoutSeconds: 30
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: config
        configMap:
          name: {{ template "oqsengine.fullname" . }}-configmap
      affinity:
      {{- if .Values.affinity }}
{{ toYaml .Values.affinity | indent 8 }}
      {{- else }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app: {{ template "oqsengine.name" . }}
                release: {{ .Release.Name }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
