replicaCount: 1

#fullnameOverride: oqsengine

image:
  repository: registry.cn-hangzhou.aliyuncs.com/xf-bm-xplat-msg/xplat-meta-oqsengine-boot
  # default .Chart.Version
  #tag: "2019.11.26-160902-develop"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port:
    http: 8086
    grpc: 8081

ingress:
  enabled: false
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 500m
    memory: 1024Mi

nodeSelector: {}

tolerations: []

affinity: {}

annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8086"
  prometheus.io/path: "/actuator/prometheus"

# 推荐-Xmx大小为limit的60%.
jvm:
  - -server
  - -XX:+UseG1GC
  - -Xmx1228m

jmx:
  enabled: false
  port: 1099
  hostname: "127.0.0.1"

environment:
  - JVM_HEAP_PERCENTAGE: 60

logger:
  level: INFO

cdc:
  connect:
    type: single
    host: 127.0.0.1
    port: 11111
    username: root
    password: root
    subscribeFilter: .*\.oqsbigentity.*
    batchSize: 2048
  consumer:
    checkCommitReady: true
    skipCommitId: -1

meta:
  grpc:
    type: client
    host: localhost
    port: 8082
    seconds:
      # 心跳超时
      heartbeatTimeout: 30
      # 重试间隔
      delaytaskTimeout: 30
      # 心跳间隔
      keepAliveDuration: 5
      # 指标监控
      monitorDuration: 1
      # 重连间隔
      reconnectDuration: 5

query:
  # 查询的最大匹配数量.
  maxVisibleTotalCount: 10000
  join:
    # join查询时的驱动表匹配上限,此值不能大于 maxVisibleTotalCount
    maxJoinEntityNumber: 2
    # join查询时的主表+驱动表的数量最大上限.
    maxJoinDriverLineNumber: 1000
changelog:
  enabled: false
storage:
  tokenizer:
    segmentation:
      lexicon:
        # 字典URL
        url: "-"
  debug:
    showsql: false
  # Maximum amount of visible data.
  maxVisibleNumber: 10000
  threadPool:
    # 0 or not exist use cpu core + 1
    call:
      read:
        worker: 256
        queue: 1000
      write:
        worker: 128
        queue: 1000
      rebuild:
        worker: 0
        queue: 1000
    cdc:
      worker: 1
    event:
      worker: 3
      queue: 1000
  transaction:
    # The transaction is valid for a period of time that will be rollback.
    timeoutMs: 3000
  timeoutMs:
    query: 3000
  master:
    name: "oqsbigentity"
    shard:
      table:
        # Whether sub-tables are needed and the number of sub-tables.
        enabled: false
        size: 1
  index:
    search:
      name: "oqsindex"
      maxQueryTimeMs: 0
      maxBatchSize: 50
    write:
      name: "oqsindex"
      shard:
        enabled: false
        size: 1
  devOps:
    cdc:
      errors:
        name: "cdcerrors"
    maxQueryTimeMs: 3000
    task:
      split: 10
      max:
        queue:
          size: 2000
      execution:
        timeout: 300000
      cache:
        expire: 30
        maxsize: 500
      page:
        size: 1000

redis:
  uri: "redis://localhost:6379"
  maxReqQueue: 2147483647

sync:
  ignoreCDCStatusCheck: false
  # The heartbeat delay of data synchronization. Milliseconds.
  allowMaxLiveTimeMs: 3000
  # Acceptable number of unsynchronized commit Numbers.
  allowMaxUnSyncCommitIdSize: 1000

# datasource json config
# Multiple data sources are separated by Numbers.
# The HikariCP connection pool implementation is used, see configuration parameters.
# see https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby
# Note that mysql default connection idle time is 8 hours and manticore is 15 minutes.
datasource:
  master: |-
    {
      driverClassName: "com.mysql.cj.jdbc.Driver"
      jdbcUrl: "jdbc:mysql://127.0.0.1:3306/oqsengine?useUnicode=true&serverTimezone=GMT&useSSL=false&characterEncoding=utf8"
      username: "root",
      password: "root",
      maximumPoolSize: 3,
      maxLifetime: 25200000,
      connectionTimeout: 30000,
      validationTimeout: 10000
    }
  index:
    # Note that the url of the index must take the following parameters.
    # maxAllowedPacket=512000&useHostsInPrivileges=false&useLocalSessionState=true&serverTimezone=Asia/Shanghai
    write: |-
      {
        driverClassName: "com.mysql.cj.jdbc.Driver"
        jdbcUrl: "jdbc:mysql://127.0.0.1:9306/oqsengine?characterEncoding=utf8&maxAllowedPacket=512000&useHostsInPrivileges=false&useLocalSessionState=true&serverTimezone=Asia/Shanghai"
        username: "root",
        password: "root",
        maximumPoolSize: 3,
        maxLifetime: 600000,
        connectionTestQuery: "select 1",
        connectionTimeout: 30000,
        validationTimeout: 10000
      }
    search: |-
      {
        driverClassName: "com.mysql.cj.jdbc.Driver"
        jdbcUrl: "jdbc:mysql://127.0.0.1:9306/oqsengine?characterEncoding=utf8&maxAllowedPacket=512000&useHostsInPrivileges=false&useLocalSessionState=true&serverTimezone=Asia/Shanghai"
        username: "root",
        password: "root",
        maximumPoolSize: 3,
        maxLifetime: 600000,
        connectionTestQuery: "select 1",
        connectionTimeout: 30000,
        validationTimeout: 10000
      }