// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package com.xforceplus.ultraman.oqsengine.sdk;

public interface EntityUpOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EntityUp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>repeated .RelationUp relation = 2;</code>
   */
  java.util.List<com.xforceplus.ultraman.oqsengine.sdk.RelationUp> 
      getRelationList();
  /**
   * <code>repeated .RelationUp relation = 2;</code>
   */
  com.xforceplus.ultraman.oqsengine.sdk.RelationUp getRelation(int index);
  /**
   * <code>repeated .RelationUp relation = 2;</code>
   */
  int getRelationCount();
  /**
   * <code>repeated .RelationUp relation = 2;</code>
   */
  java.util.List<? extends com.xforceplus.ultraman.oqsengine.sdk.RelationUpOrBuilder> 
      getRelationOrBuilderList();
  /**
   * <code>repeated .RelationUp relation = 2;</code>
   */
  com.xforceplus.ultraman.oqsengine.sdk.RelationUpOrBuilder getRelationOrBuilder(
      int index);

  /**
   * <code>repeated .EntityUp entityClasses = 3;</code>
   */
  java.util.List<com.xforceplus.ultraman.oqsengine.sdk.EntityUp> 
      getEntityClassesList();
  /**
   * <code>repeated .EntityUp entityClasses = 3;</code>
   */
  com.xforceplus.ultraman.oqsengine.sdk.EntityUp getEntityClasses(int index);
  /**
   * <code>repeated .EntityUp entityClasses = 3;</code>
   */
  int getEntityClassesCount();
  /**
   * <code>repeated .EntityUp entityClasses = 3;</code>
   */
  java.util.List<? extends com.xforceplus.ultraman.oqsengine.sdk.EntityUpOrBuilder> 
      getEntityClassesOrBuilderList();
  /**
   * <code>repeated .EntityUp entityClasses = 3;</code>
   */
  com.xforceplus.ultraman.oqsengine.sdk.EntityUpOrBuilder getEntityClassesOrBuilder(
      int index);

  /**
   * <code>.EntityUp extendEntityClass = 4;</code>
   * @return Whether the extendEntityClass field is set.
   */
  boolean hasExtendEntityClass();
  /**
   * <code>.EntityUp extendEntityClass = 4;</code>
   * @return The extendEntityClass.
   */
  com.xforceplus.ultraman.oqsengine.sdk.EntityUp getExtendEntityClass();
  /**
   * <code>.EntityUp extendEntityClass = 4;</code>
   */
  com.xforceplus.ultraman.oqsengine.sdk.EntityUpOrBuilder getExtendEntityClassOrBuilder();

  /**
   * <code>repeated .FieldUp fields = 5;</code>
   */
  java.util.List<com.xforceplus.ultraman.oqsengine.sdk.FieldUp> 
      getFieldsList();
  /**
   * <code>repeated .FieldUp fields = 5;</code>
   */
  com.xforceplus.ultraman.oqsengine.sdk.FieldUp getFields(int index);
  /**
   * <code>repeated .FieldUp fields = 5;</code>
   */
  int getFieldsCount();
  /**
   * <code>repeated .FieldUp fields = 5;</code>
   */
  java.util.List<? extends com.xforceplus.ultraman.oqsengine.sdk.FieldUpOrBuilder> 
      getFieldsOrBuilderList();
  /**
   * <code>repeated .FieldUp fields = 5;</code>
   */
  com.xforceplus.ultraman.oqsengine.sdk.FieldUpOrBuilder getFieldsOrBuilder(
      int index);

  /**
   * <code>repeated .ValueUp values = 6;</code>
   */
  java.util.List<com.xforceplus.ultraman.oqsengine.sdk.ValueUp> 
      getValuesList();
  /**
   * <code>repeated .ValueUp values = 6;</code>
   */
  com.xforceplus.ultraman.oqsengine.sdk.ValueUp getValues(int index);
  /**
   * <code>repeated .ValueUp values = 6;</code>
   */
  int getValuesCount();
  /**
   * <code>repeated .ValueUp values = 6;</code>
   */
  java.util.List<? extends com.xforceplus.ultraman.oqsengine.sdk.ValueUpOrBuilder> 
      getValuesOrBuilderList();
  /**
   * <code>repeated .ValueUp values = 6;</code>
   */
  com.xforceplus.ultraman.oqsengine.sdk.ValueUpOrBuilder getValuesOrBuilder(
      int index);

  /**
   * <code>int64 objId = 7;</code>
   * @return The objId.
   */
  long getObjId();

  /**
   * <code>string code = 8;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 8;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>.EntityUp subEntityClass = 9;</code>
   * @return Whether the subEntityClass field is set.
   */
  boolean hasSubEntityClass();
  /**
   * <code>.EntityUp subEntityClass = 9;</code>
   * @return The subEntityClass.
   */
  com.xforceplus.ultraman.oqsengine.sdk.EntityUp getSubEntityClass();
  /**
   * <code>.EntityUp subEntityClass = 9;</code>
   */
  com.xforceplus.ultraman.oqsengine.sdk.EntityUpOrBuilder getSubEntityClassOrBuilder();
}
