// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rebuild.proto

package com.xforceplus.ultraman.oqsengine.sdk;

/**
 * Protobuf type {@code EntityUpList}
 */
public  final class EntityUpList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EntityUpList)
    EntityUpListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EntityUpList.newBuilder() to construct.
  private EntityUpList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EntityUpList() {
    ups_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EntityUpList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EntityUpList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              ups_ = new java.util.ArrayList<com.xforceplus.ultraman.oqsengine.sdk.EntityUp>();
              mutable_bitField0_ |= 0x00000001;
            }
            ups_.add(
                input.readMessage(com.xforceplus.ultraman.oqsengine.sdk.EntityUp.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        ups_ = java.util.Collections.unmodifiableList(ups_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xforceplus.ultraman.oqsengine.sdk.EntityRebuildResourceProto.internal_static_EntityUpList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xforceplus.ultraman.oqsengine.sdk.EntityRebuildResourceProto.internal_static_EntityUpList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xforceplus.ultraman.oqsengine.sdk.EntityUpList.class, com.xforceplus.ultraman.oqsengine.sdk.EntityUpList.Builder.class);
  }

  public static final int UPS_FIELD_NUMBER = 1;
  private java.util.List<com.xforceplus.ultraman.oqsengine.sdk.EntityUp> ups_;
  /**
   * <code>repeated .EntityUp ups = 1;</code>
   */
  public java.util.List<com.xforceplus.ultraman.oqsengine.sdk.EntityUp> getUpsList() {
    return ups_;
  }
  /**
   * <code>repeated .EntityUp ups = 1;</code>
   */
  public java.util.List<? extends com.xforceplus.ultraman.oqsengine.sdk.EntityUpOrBuilder> 
      getUpsOrBuilderList() {
    return ups_;
  }
  /**
   * <code>repeated .EntityUp ups = 1;</code>
   */
  public int getUpsCount() {
    return ups_.size();
  }
  /**
   * <code>repeated .EntityUp ups = 1;</code>
   */
  public com.xforceplus.ultraman.oqsengine.sdk.EntityUp getUps(int index) {
    return ups_.get(index);
  }
  /**
   * <code>repeated .EntityUp ups = 1;</code>
   */
  public com.xforceplus.ultraman.oqsengine.sdk.EntityUpOrBuilder getUpsOrBuilder(
      int index) {
    return ups_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < ups_.size(); i++) {
      output.writeMessage(1, ups_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < ups_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, ups_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xforceplus.ultraman.oqsengine.sdk.EntityUpList)) {
      return super.equals(obj);
    }
    com.xforceplus.ultraman.oqsengine.sdk.EntityUpList other = (com.xforceplus.ultraman.oqsengine.sdk.EntityUpList) obj;

    if (!getUpsList()
        .equals(other.getUpsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUpsCount() > 0) {
      hash = (37 * hash) + UPS_FIELD_NUMBER;
      hash = (53 * hash) + getUpsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xforceplus.ultraman.oqsengine.sdk.EntityUpList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xforceplus.ultraman.oqsengine.sdk.EntityUpList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.sdk.EntityUpList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xforceplus.ultraman.oqsengine.sdk.EntityUpList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.sdk.EntityUpList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xforceplus.ultraman.oqsengine.sdk.EntityUpList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.sdk.EntityUpList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xforceplus.ultraman.oqsengine.sdk.EntityUpList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.sdk.EntityUpList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xforceplus.ultraman.oqsengine.sdk.EntityUpList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.sdk.EntityUpList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xforceplus.ultraman.oqsengine.sdk.EntityUpList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xforceplus.ultraman.oqsengine.sdk.EntityUpList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code EntityUpList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EntityUpList)
      com.xforceplus.ultraman.oqsengine.sdk.EntityUpListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xforceplus.ultraman.oqsengine.sdk.EntityRebuildResourceProto.internal_static_EntityUpList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xforceplus.ultraman.oqsengine.sdk.EntityRebuildResourceProto.internal_static_EntityUpList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xforceplus.ultraman.oqsengine.sdk.EntityUpList.class, com.xforceplus.ultraman.oqsengine.sdk.EntityUpList.Builder.class);
    }

    // Construct using com.xforceplus.ultraman.oqsengine.sdk.EntityUpList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUpsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (upsBuilder_ == null) {
        ups_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        upsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xforceplus.ultraman.oqsengine.sdk.EntityRebuildResourceProto.internal_static_EntityUpList_descriptor;
    }

    @java.lang.Override
    public com.xforceplus.ultraman.oqsengine.sdk.EntityUpList getDefaultInstanceForType() {
      return com.xforceplus.ultraman.oqsengine.sdk.EntityUpList.getDefaultInstance();
    }

    @java.lang.Override
    public com.xforceplus.ultraman.oqsengine.sdk.EntityUpList build() {
      com.xforceplus.ultraman.oqsengine.sdk.EntityUpList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xforceplus.ultraman.oqsengine.sdk.EntityUpList buildPartial() {
      com.xforceplus.ultraman.oqsengine.sdk.EntityUpList result = new com.xforceplus.ultraman.oqsengine.sdk.EntityUpList(this);
      int from_bitField0_ = bitField0_;
      if (upsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          ups_ = java.util.Collections.unmodifiableList(ups_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ups_ = ups_;
      } else {
        result.ups_ = upsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xforceplus.ultraman.oqsengine.sdk.EntityUpList) {
        return mergeFrom((com.xforceplus.ultraman.oqsengine.sdk.EntityUpList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xforceplus.ultraman.oqsengine.sdk.EntityUpList other) {
      if (other == com.xforceplus.ultraman.oqsengine.sdk.EntityUpList.getDefaultInstance()) return this;
      if (upsBuilder_ == null) {
        if (!other.ups_.isEmpty()) {
          if (ups_.isEmpty()) {
            ups_ = other.ups_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUpsIsMutable();
            ups_.addAll(other.ups_);
          }
          onChanged();
        }
      } else {
        if (!other.ups_.isEmpty()) {
          if (upsBuilder_.isEmpty()) {
            upsBuilder_.dispose();
            upsBuilder_ = null;
            ups_ = other.ups_;
            bitField0_ = (bitField0_ & ~0x00000001);
            upsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUpsFieldBuilder() : null;
          } else {
            upsBuilder_.addAllMessages(other.ups_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xforceplus.ultraman.oqsengine.sdk.EntityUpList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xforceplus.ultraman.oqsengine.sdk.EntityUpList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.xforceplus.ultraman.oqsengine.sdk.EntityUp> ups_ =
      java.util.Collections.emptyList();
    private void ensureUpsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        ups_ = new java.util.ArrayList<com.xforceplus.ultraman.oqsengine.sdk.EntityUp>(ups_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xforceplus.ultraman.oqsengine.sdk.EntityUp, com.xforceplus.ultraman.oqsengine.sdk.EntityUp.Builder, com.xforceplus.ultraman.oqsengine.sdk.EntityUpOrBuilder> upsBuilder_;

    /**
     * <code>repeated .EntityUp ups = 1;</code>
     */
    public java.util.List<com.xforceplus.ultraman.oqsengine.sdk.EntityUp> getUpsList() {
      if (upsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ups_);
      } else {
        return upsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .EntityUp ups = 1;</code>
     */
    public int getUpsCount() {
      if (upsBuilder_ == null) {
        return ups_.size();
      } else {
        return upsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .EntityUp ups = 1;</code>
     */
    public com.xforceplus.ultraman.oqsengine.sdk.EntityUp getUps(int index) {
      if (upsBuilder_ == null) {
        return ups_.get(index);
      } else {
        return upsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .EntityUp ups = 1;</code>
     */
    public Builder setUps(
        int index, com.xforceplus.ultraman.oqsengine.sdk.EntityUp value) {
      if (upsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpsIsMutable();
        ups_.set(index, value);
        onChanged();
      } else {
        upsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .EntityUp ups = 1;</code>
     */
    public Builder setUps(
        int index, com.xforceplus.ultraman.oqsengine.sdk.EntityUp.Builder builderForValue) {
      if (upsBuilder_ == null) {
        ensureUpsIsMutable();
        ups_.set(index, builderForValue.build());
        onChanged();
      } else {
        upsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EntityUp ups = 1;</code>
     */
    public Builder addUps(com.xforceplus.ultraman.oqsengine.sdk.EntityUp value) {
      if (upsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpsIsMutable();
        ups_.add(value);
        onChanged();
      } else {
        upsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .EntityUp ups = 1;</code>
     */
    public Builder addUps(
        int index, com.xforceplus.ultraman.oqsengine.sdk.EntityUp value) {
      if (upsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpsIsMutable();
        ups_.add(index, value);
        onChanged();
      } else {
        upsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .EntityUp ups = 1;</code>
     */
    public Builder addUps(
        com.xforceplus.ultraman.oqsengine.sdk.EntityUp.Builder builderForValue) {
      if (upsBuilder_ == null) {
        ensureUpsIsMutable();
        ups_.add(builderForValue.build());
        onChanged();
      } else {
        upsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EntityUp ups = 1;</code>
     */
    public Builder addUps(
        int index, com.xforceplus.ultraman.oqsengine.sdk.EntityUp.Builder builderForValue) {
      if (upsBuilder_ == null) {
        ensureUpsIsMutable();
        ups_.add(index, builderForValue.build());
        onChanged();
      } else {
        upsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EntityUp ups = 1;</code>
     */
    public Builder addAllUps(
        java.lang.Iterable<? extends com.xforceplus.ultraman.oqsengine.sdk.EntityUp> values) {
      if (upsBuilder_ == null) {
        ensureUpsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ups_);
        onChanged();
      } else {
        upsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .EntityUp ups = 1;</code>
     */
    public Builder clearUps() {
      if (upsBuilder_ == null) {
        ups_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        upsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .EntityUp ups = 1;</code>
     */
    public Builder removeUps(int index) {
      if (upsBuilder_ == null) {
        ensureUpsIsMutable();
        ups_.remove(index);
        onChanged();
      } else {
        upsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .EntityUp ups = 1;</code>
     */
    public com.xforceplus.ultraman.oqsengine.sdk.EntityUp.Builder getUpsBuilder(
        int index) {
      return getUpsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .EntityUp ups = 1;</code>
     */
    public com.xforceplus.ultraman.oqsengine.sdk.EntityUpOrBuilder getUpsOrBuilder(
        int index) {
      if (upsBuilder_ == null) {
        return ups_.get(index);  } else {
        return upsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .EntityUp ups = 1;</code>
     */
    public java.util.List<? extends com.xforceplus.ultraman.oqsengine.sdk.EntityUpOrBuilder> 
         getUpsOrBuilderList() {
      if (upsBuilder_ != null) {
        return upsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ups_);
      }
    }
    /**
     * <code>repeated .EntityUp ups = 1;</code>
     */
    public com.xforceplus.ultraman.oqsengine.sdk.EntityUp.Builder addUpsBuilder() {
      return getUpsFieldBuilder().addBuilder(
          com.xforceplus.ultraman.oqsengine.sdk.EntityUp.getDefaultInstance());
    }
    /**
     * <code>repeated .EntityUp ups = 1;</code>
     */
    public com.xforceplus.ultraman.oqsengine.sdk.EntityUp.Builder addUpsBuilder(
        int index) {
      return getUpsFieldBuilder().addBuilder(
          index, com.xforceplus.ultraman.oqsengine.sdk.EntityUp.getDefaultInstance());
    }
    /**
     * <code>repeated .EntityUp ups = 1;</code>
     */
    public java.util.List<com.xforceplus.ultraman.oqsengine.sdk.EntityUp.Builder> 
         getUpsBuilderList() {
      return getUpsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xforceplus.ultraman.oqsengine.sdk.EntityUp, com.xforceplus.ultraman.oqsengine.sdk.EntityUp.Builder, com.xforceplus.ultraman.oqsengine.sdk.EntityUpOrBuilder> 
        getUpsFieldBuilder() {
      if (upsBuilder_ == null) {
        upsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.xforceplus.ultraman.oqsengine.sdk.EntityUp, com.xforceplus.ultraman.oqsengine.sdk.EntityUp.Builder, com.xforceplus.ultraman.oqsengine.sdk.EntityUpOrBuilder>(
                ups_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        ups_ = null;
      }
      return upsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:EntityUpList)
  }

  // @@protoc_insertion_point(class_scope:EntityUpList)
  private static final com.xforceplus.ultraman.oqsengine.sdk.EntityUpList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xforceplus.ultraman.oqsengine.sdk.EntityUpList();
  }

  public static com.xforceplus.ultraman.oqsengine.sdk.EntityUpList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EntityUpList>
      PARSER = new com.google.protobuf.AbstractParser<EntityUpList>() {
    @java.lang.Override
    public EntityUpList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EntityUpList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EntityUpList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EntityUpList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xforceplus.ultraman.oqsengine.sdk.EntityUpList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

