// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package com.xforceplus.ultraman.oqsengine.sdk;

public interface FieldUpOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FieldUp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *字段id
   * </pre>
   *
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <pre>
   * 字段名称
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  String getName();
  /**
   * <pre>
   * 字段名称
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * 字段类型
   * </pre>
   *
   * <code>string fieldType = 3;</code>
   */
  String getFieldType();
  /**
   * <pre>
   * 字段类型
   * </pre>
   *
   * <code>string fieldType = 3;</code>
   */
  com.google.protobuf.ByteString
      getFieldTypeBytes();

  /**
   * <code>string code = 4;</code>
   */
  String getCode();
  /**
   * <code>string code = 4;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string displayType = 5;</code>
   */
  String getDisplayType();
  /**
   * <code>string displayType = 5;</code>
   */
  com.google.protobuf.ByteString
      getDisplayTypeBytes();

  /**
   * <code>string editable = 6;</code>
   */
  String getEditable();
  /**
   * <code>string editable = 6;</code>
   */
  com.google.protobuf.ByteString
      getEditableBytes();

  /**
   * <code>string enumCode = 7;</code>
   */
  String getEnumCode();
  /**
   * <code>string enumCode = 7;</code>
   */
  com.google.protobuf.ByteString
      getEnumCodeBytes();

  /**
   * <code>string maxLength = 8;</code>
   */
  String getMaxLength();
  /**
   * <code>string maxLength = 8;</code>
   */
  com.google.protobuf.ByteString
      getMaxLengthBytes();

  /**
   * <code>string required = 9;</code>
   */
  String getRequired();
  /**
   * <code>string required = 9;</code>
   */
  com.google.protobuf.ByteString
      getRequiredBytes();

  /**
   * <code>string searchable = 10;</code>
   */
  String getSearchable();
  /**
   * <code>string searchable = 10;</code>
   */
  com.google.protobuf.ByteString
      getSearchableBytes();

  /**
   * <code>string minLength = 11;</code>
   */
  String getMinLength();
  /**
   * <code>string minLength = 11;</code>
   */
  com.google.protobuf.ByteString
      getMinLengthBytes();
}
