// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package com.xforceplus.ultraman.oqsengine.sdk;

/**
 * Protobuf type {@code FieldSortUp}
 */
public  final class FieldSortUp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FieldSortUp)
    FieldSortUpOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FieldSortUp.newBuilder() to construct.
  private FieldSortUp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FieldSortUp() {
    code_ = "";
    order_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FieldSortUp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FieldSortUp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            code_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            order_ = rawValue;
            break;
          }
          case 26: {
            com.xforceplus.ultraman.oqsengine.sdk.FieldUp.Builder subBuilder = null;
            if (field_ != null) {
              subBuilder = field_.toBuilder();
            }
            field_ = input.readMessage(com.xforceplus.ultraman.oqsengine.sdk.FieldUp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(field_);
              field_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xforceplus.ultraman.oqsengine.sdk.EntityResourceProto.internal_static_FieldSortUp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xforceplus.ultraman.oqsengine.sdk.EntityResourceProto.internal_static_FieldSortUp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp.class, com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp.Builder.class);
  }

  /**
   * Protobuf enum {@code FieldSortUp.Order}
   */
  public enum Order
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>asc = 0;</code>
     */
    asc(0),
    /**
     * <code>desc = 1;</code>
     */
    desc(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>asc = 0;</code>
     */
    public static final int asc_VALUE = 0;
    /**
     * <code>desc = 1;</code>
     */
    public static final int desc_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Order valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Order forNumber(int value) {
      switch (value) {
        case 0: return asc;
        case 1: return desc;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Order>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Order> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Order>() {
            public Order findValueByNumber(int number) {
              return Order.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp.getDescriptor().getEnumTypes().get(0);
    }

    private static final Order[] VALUES = values();

    public static Order valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Order(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:FieldSortUp.Order)
  }

  public static final int CODE_FIELD_NUMBER = 1;
  private volatile java.lang.Object code_;
  /**
   * <code>string code = 1;</code>
   * @return The code.
   */
  public java.lang.String getCode() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      code_ = s;
      return s;
    }
  }
  /**
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  public com.google.protobuf.ByteString
      getCodeBytes() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      code_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORDER_FIELD_NUMBER = 2;
  private int order_;
  /**
   * <code>.FieldSortUp.Order order = 2;</code>
   * @return The enum numeric value on the wire for order.
   */
  public int getOrderValue() {
    return order_;
  }
  /**
   * <code>.FieldSortUp.Order order = 2;</code>
   * @return The order.
   */
  public com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp.Order getOrder() {
    @SuppressWarnings("deprecation")
    com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp.Order result = com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp.Order.valueOf(order_);
    return result == null ? com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp.Order.UNRECOGNIZED : result;
  }

  public static final int FIELD_FIELD_NUMBER = 3;
  private com.xforceplus.ultraman.oqsengine.sdk.FieldUp field_;
  /**
   * <code>.FieldUp field = 3;</code>
   * @return Whether the field field is set.
   */
  public boolean hasField() {
    return field_ != null;
  }
  /**
   * <code>.FieldUp field = 3;</code>
   * @return The field.
   */
  public com.xforceplus.ultraman.oqsengine.sdk.FieldUp getField() {
    return field_ == null ? com.xforceplus.ultraman.oqsengine.sdk.FieldUp.getDefaultInstance() : field_;
  }
  /**
   * <code>.FieldUp field = 3;</code>
   */
  public com.xforceplus.ultraman.oqsengine.sdk.FieldUpOrBuilder getFieldOrBuilder() {
    return getField();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, code_);
    }
    if (order_ != com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp.Order.asc.getNumber()) {
      output.writeEnum(2, order_);
    }
    if (field_ != null) {
      output.writeMessage(3, getField());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, code_);
    }
    if (order_ != com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp.Order.asc.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, order_);
    }
    if (field_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getField());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp)) {
      return super.equals(obj);
    }
    com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp other = (com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp) obj;

    if (!getCode()
        .equals(other.getCode())) return false;
    if (order_ != other.order_) return false;
    if (hasField() != other.hasField()) return false;
    if (hasField()) {
      if (!getField()
          .equals(other.getField())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode().hashCode();
    hash = (37 * hash) + ORDER_FIELD_NUMBER;
    hash = (53 * hash) + order_;
    if (hasField()) {
      hash = (37 * hash) + FIELD_FIELD_NUMBER;
      hash = (53 * hash) + getField().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FieldSortUp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FieldSortUp)
      com.xforceplus.ultraman.oqsengine.sdk.FieldSortUpOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xforceplus.ultraman.oqsengine.sdk.EntityResourceProto.internal_static_FieldSortUp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xforceplus.ultraman.oqsengine.sdk.EntityResourceProto.internal_static_FieldSortUp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp.class, com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp.Builder.class);
    }

    // Construct using com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      code_ = "";

      order_ = 0;

      if (fieldBuilder_ == null) {
        field_ = null;
      } else {
        field_ = null;
        fieldBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xforceplus.ultraman.oqsengine.sdk.EntityResourceProto.internal_static_FieldSortUp_descriptor;
    }

    @java.lang.Override
    public com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp getDefaultInstanceForType() {
      return com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp.getDefaultInstance();
    }

    @java.lang.Override
    public com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp build() {
      com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp buildPartial() {
      com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp result = new com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp(this);
      result.code_ = code_;
      result.order_ = order_;
      if (fieldBuilder_ == null) {
        result.field_ = field_;
      } else {
        result.field_ = fieldBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp) {
        return mergeFrom((com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp other) {
      if (other == com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp.getDefaultInstance()) return this;
      if (!other.getCode().isEmpty()) {
        code_ = other.code_;
        onChanged();
      }
      if (other.order_ != 0) {
        setOrderValue(other.getOrderValue());
      }
      if (other.hasField()) {
        mergeField(other.getField());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object code_ = "";
    /**
     * <code>string code = 1;</code>
     * @return The code.
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string code = 1;</code>
     * @return The bytes for code.
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string code = 1;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      
      code_ = getDefaultInstance().getCode();
      onChanged();
      return this;
    }
    /**
     * <code>string code = 1;</code>
     * @param value The bytes for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      code_ = value;
      onChanged();
      return this;
    }

    private int order_ = 0;
    /**
     * <code>.FieldSortUp.Order order = 2;</code>
     * @return The enum numeric value on the wire for order.
     */
    public int getOrderValue() {
      return order_;
    }
    /**
     * <code>.FieldSortUp.Order order = 2;</code>
     * @param value The enum numeric value on the wire for order to set.
     * @return This builder for chaining.
     */
    public Builder setOrderValue(int value) {
      order_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.FieldSortUp.Order order = 2;</code>
     * @return The order.
     */
    public com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp.Order getOrder() {
      @SuppressWarnings("deprecation")
      com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp.Order result = com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp.Order.valueOf(order_);
      return result == null ? com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp.Order.UNRECOGNIZED : result;
    }
    /**
     * <code>.FieldSortUp.Order order = 2;</code>
     * @param value The order to set.
     * @return This builder for chaining.
     */
    public Builder setOrder(com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp.Order value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      order_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.FieldSortUp.Order order = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrder() {
      
      order_ = 0;
      onChanged();
      return this;
    }

    private com.xforceplus.ultraman.oqsengine.sdk.FieldUp field_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xforceplus.ultraman.oqsengine.sdk.FieldUp, com.xforceplus.ultraman.oqsengine.sdk.FieldUp.Builder, com.xforceplus.ultraman.oqsengine.sdk.FieldUpOrBuilder> fieldBuilder_;
    /**
     * <code>.FieldUp field = 3;</code>
     * @return Whether the field field is set.
     */
    public boolean hasField() {
      return fieldBuilder_ != null || field_ != null;
    }
    /**
     * <code>.FieldUp field = 3;</code>
     * @return The field.
     */
    public com.xforceplus.ultraman.oqsengine.sdk.FieldUp getField() {
      if (fieldBuilder_ == null) {
        return field_ == null ? com.xforceplus.ultraman.oqsengine.sdk.FieldUp.getDefaultInstance() : field_;
      } else {
        return fieldBuilder_.getMessage();
      }
    }
    /**
     * <code>.FieldUp field = 3;</code>
     */
    public Builder setField(com.xforceplus.ultraman.oqsengine.sdk.FieldUp value) {
      if (fieldBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        field_ = value;
        onChanged();
      } else {
        fieldBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.FieldUp field = 3;</code>
     */
    public Builder setField(
        com.xforceplus.ultraman.oqsengine.sdk.FieldUp.Builder builderForValue) {
      if (fieldBuilder_ == null) {
        field_ = builderForValue.build();
        onChanged();
      } else {
        fieldBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.FieldUp field = 3;</code>
     */
    public Builder mergeField(com.xforceplus.ultraman.oqsengine.sdk.FieldUp value) {
      if (fieldBuilder_ == null) {
        if (field_ != null) {
          field_ =
            com.xforceplus.ultraman.oqsengine.sdk.FieldUp.newBuilder(field_).mergeFrom(value).buildPartial();
        } else {
          field_ = value;
        }
        onChanged();
      } else {
        fieldBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.FieldUp field = 3;</code>
     */
    public Builder clearField() {
      if (fieldBuilder_ == null) {
        field_ = null;
        onChanged();
      } else {
        field_ = null;
        fieldBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.FieldUp field = 3;</code>
     */
    public com.xforceplus.ultraman.oqsengine.sdk.FieldUp.Builder getFieldBuilder() {
      
      onChanged();
      return getFieldFieldBuilder().getBuilder();
    }
    /**
     * <code>.FieldUp field = 3;</code>
     */
    public com.xforceplus.ultraman.oqsengine.sdk.FieldUpOrBuilder getFieldOrBuilder() {
      if (fieldBuilder_ != null) {
        return fieldBuilder_.getMessageOrBuilder();
      } else {
        return field_ == null ?
            com.xforceplus.ultraman.oqsengine.sdk.FieldUp.getDefaultInstance() : field_;
      }
    }
    /**
     * <code>.FieldUp field = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xforceplus.ultraman.oqsengine.sdk.FieldUp, com.xforceplus.ultraman.oqsengine.sdk.FieldUp.Builder, com.xforceplus.ultraman.oqsengine.sdk.FieldUpOrBuilder> 
        getFieldFieldBuilder() {
      if (fieldBuilder_ == null) {
        fieldBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xforceplus.ultraman.oqsengine.sdk.FieldUp, com.xforceplus.ultraman.oqsengine.sdk.FieldUp.Builder, com.xforceplus.ultraman.oqsengine.sdk.FieldUpOrBuilder>(
                getField(),
                getParentForChildren(),
                isClean());
        field_ = null;
      }
      return fieldBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FieldSortUp)
  }

  // @@protoc_insertion_point(class_scope:FieldSortUp)
  private static final com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp();
  }

  public static com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FieldSortUp>
      PARSER = new com.google.protobuf.AbstractParser<FieldSortUp>() {
    @java.lang.Override
    public FieldSortUp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FieldSortUp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FieldSortUp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FieldSortUp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

