// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package com.xforceplus.ultraman.oqsengine.sdk;

public interface SelectByConditionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SelectByCondition)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.EntityUp entity = 1;</code>
   * @return Whether the entity field is set.
   */
  boolean hasEntity();
  /**
   * <code>.EntityUp entity = 1;</code>
   * @return The entity.
   */
  com.xforceplus.ultraman.oqsengine.sdk.EntityUp getEntity();
  /**
   * <code>.EntityUp entity = 1;</code>
   */
  com.xforceplus.ultraman.oqsengine.sdk.EntityUpOrBuilder getEntityOrBuilder();

  /**
   * <code>int32 pageNo = 2;</code>
   * @return The pageNo.
   */
  int getPageNo();

  /**
   * <code>int32 pageSize = 3;</code>
   * @return The pageSize.
   */
  int getPageSize();

  /**
   * <code>.ConditionsUp conditions = 4;</code>
   * @return Whether the conditions field is set.
   */
  boolean hasConditions();
  /**
   * <code>.ConditionsUp conditions = 4;</code>
   * @return The conditions.
   */
  com.xforceplus.ultraman.oqsengine.sdk.ConditionsUp getConditions();
  /**
   * <code>.ConditionsUp conditions = 4;</code>
   */
  com.xforceplus.ultraman.oqsengine.sdk.ConditionsUpOrBuilder getConditionsOrBuilder();

  /**
   * <code>repeated .FieldSortUp sort = 5;</code>
   */
  java.util.List<com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp> 
      getSortList();
  /**
   * <code>repeated .FieldSortUp sort = 5;</code>
   */
  com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp getSort(int index);
  /**
   * <code>repeated .FieldSortUp sort = 5;</code>
   */
  int getSortCount();
  /**
   * <code>repeated .FieldSortUp sort = 5;</code>
   */
  java.util.List<? extends com.xforceplus.ultraman.oqsengine.sdk.FieldSortUpOrBuilder> 
      getSortOrBuilderList();
  /**
   * <code>repeated .FieldSortUp sort = 5;</code>
   */
  com.xforceplus.ultraman.oqsengine.sdk.FieldSortUpOrBuilder getSortOrBuilder(
      int index);

  /**
   * <code>repeated .QueryFieldsUp queryFields = 6;</code>
   */
  java.util.List<com.xforceplus.ultraman.oqsengine.sdk.QueryFieldsUp> 
      getQueryFieldsList();
  /**
   * <code>repeated .QueryFieldsUp queryFields = 6;</code>
   */
  com.xforceplus.ultraman.oqsengine.sdk.QueryFieldsUp getQueryFields(int index);
  /**
   * <code>repeated .QueryFieldsUp queryFields = 6;</code>
   */
  int getQueryFieldsCount();
  /**
   * <code>repeated .QueryFieldsUp queryFields = 6;</code>
   */
  java.util.List<? extends com.xforceplus.ultraman.oqsengine.sdk.QueryFieldsUpOrBuilder> 
      getQueryFieldsOrBuilderList();
  /**
   * <code>repeated .QueryFieldsUp queryFields = 6;</code>
   */
  com.xforceplus.ultraman.oqsengine.sdk.QueryFieldsUpOrBuilder getQueryFieldsOrBuilder(
      int index);

  /**
   * <code>repeated int64 ids = 7;</code>
   * @return A list containing the ids.
   */
  java.util.List<java.lang.Long> getIdsList();
  /**
   * <code>repeated int64 ids = 7;</code>
   * @return The count of ids.
   */
  int getIdsCount();
  /**
   * <code>repeated int64 ids = 7;</code>
   * @param index The index of the element to return.
   * @return The ids at the given index.
   */
  long getIds(int index);
}
