// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package com.xforceplus.ultraman.oqsengine.sdk;

public interface TransactionUpOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TransactionUp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string service = 2;</code>
   */
  String getService();
  /**
   * <code>string service = 2;</code>
   */
  com.google.protobuf.ByteString
      getServiceBytes();

  /**
   * <code>string tansType = 3;</code>
   */
  String getTansType();
  /**
   * <code>string tansType = 3;</code>
   */
  com.google.protobuf.ByteString
      getTansTypeBytes();
}
