// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sync.proto

package com.xforceplus.ultraman.oqsengine.meta.common.proto;

public interface EntityClassSyncResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EntityClassSyncResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .EntityClassSyncRspProtoCheck entityClassSyncRspProtoCheck = 1;</code>
   */
  java.util.List<com.xforceplus.ultraman.oqsengine.meta.common.proto.EntityClassSyncRspProtoCheck> 
      getEntityClassSyncRspProtoCheckList();
  /**
   * <code>repeated .EntityClassSyncRspProtoCheck entityClassSyncRspProtoCheck = 1;</code>
   */
  com.xforceplus.ultraman.oqsengine.meta.common.proto.EntityClassSyncRspProtoCheck getEntityClassSyncRspProtoCheck(int index);
  /**
   * <code>repeated .EntityClassSyncRspProtoCheck entityClassSyncRspProtoCheck = 1;</code>
   */
  int getEntityClassSyncRspProtoCheckCount();
  /**
   * <code>repeated .EntityClassSyncRspProtoCheck entityClassSyncRspProtoCheck = 1;</code>
   */
  java.util.List<? extends com.xforceplus.ultraman.oqsengine.meta.common.proto.EntityClassSyncRspProtoCheckOrBuilder> 
      getEntityClassSyncRspProtoCheckOrBuilderList();
  /**
   * <code>repeated .EntityClassSyncRspProtoCheck entityClassSyncRspProtoCheck = 1;</code>
   */
  com.xforceplus.ultraman.oqsengine.meta.common.proto.EntityClassSyncRspProtoCheckOrBuilder getEntityClassSyncRspProtoCheckOrBuilder(
      int index);
}
