// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ForBo.proto

package com.xforceplus.ultraman.oqsengine.meta.proto.test;

public interface FieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Field)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *字段id
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <pre>
   *字段id
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * 字段名称
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * 字段名称
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * 字段类型
   * </pre>
   *
   * <code>string fieldType = 3;</code>
   */
  java.lang.String getFieldType();
  /**
   * <pre>
   * 字段类型
   * </pre>
   *
   * <code>string fieldType = 3;</code>
   */
  com.google.protobuf.ByteString
      getFieldTypeBytes();

  /**
   * <code>string code = 4;</code>
   */
  java.lang.String getCode();
  /**
   * <code>string code = 4;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string displayType = 5;</code>
   */
  java.lang.String getDisplayType();
  /**
   * <code>string displayType = 5;</code>
   */
  com.google.protobuf.ByteString
      getDisplayTypeBytes();

  /**
   * <code>string editable = 6;</code>
   */
  java.lang.String getEditable();
  /**
   * <code>string editable = 6;</code>
   */
  com.google.protobuf.ByteString
      getEditableBytes();

  /**
   * <code>string enumCode = 7;</code>
   */
  java.lang.String getEnumCode();
  /**
   * <code>string enumCode = 7;</code>
   */
  com.google.protobuf.ByteString
      getEnumCodeBytes();

  /**
   * <code>string maxLength = 8;</code>
   */
  java.lang.String getMaxLength();
  /**
   * <code>string maxLength = 8;</code>
   */
  com.google.protobuf.ByteString
      getMaxLengthBytes();

  /**
   * <code>string required = 9;</code>
   */
  java.lang.String getRequired();
  /**
   * <code>string required = 9;</code>
   */
  com.google.protobuf.ByteString
      getRequiredBytes();

  /**
   * <code>string searchable = 10;</code>
   */
  java.lang.String getSearchable();
  /**
   * <code>string searchable = 10;</code>
   */
  com.google.protobuf.ByteString
      getSearchableBytes();

  /**
   * <code>string dictId = 11;</code>
   */
  java.lang.String getDictId();
  /**
   * <code>string dictId = 11;</code>
   */
  com.google.protobuf.ByteString
      getDictIdBytes();

  /**
   * <code>string defaultValue = 12;</code>
   */
  java.lang.String getDefaultValue();
  /**
   * <code>string defaultValue = 12;</code>
   */
  com.google.protobuf.ByteString
      getDefaultValueBytes();

  /**
   * <code>int32 precision = 13;</code>
   */
  int getPrecision();

  /**
   * <code>string identifier = 14;</code>
   */
  java.lang.String getIdentifier();
  /**
   * <code>string identifier = 14;</code>
   */
  com.google.protobuf.ByteString
      getIdentifierBytes();

  /**
   * <code>string validateRule = 15;</code>
   */
  java.lang.String getValidateRule();
  /**
   * <code>string validateRule = 15;</code>
   */
  com.google.protobuf.ByteString
      getValidateRuleBytes();

  /**
   * <code>int32 describeType = 16;</code>
   */
  int getDescribeType();

  /**
   * <code>string uniqueName = 17;</code>
   */
  java.lang.String getUniqueName();
  /**
   * <code>string uniqueName = 17;</code>
   */
  com.google.protobuf.ByteString
      getUniqueNameBytes();

  /**
   * <code>string indexFlag = 18;</code>
   */
  java.lang.String getIndexFlag();
  /**
   * <code>string indexFlag = 18;</code>
   */
  com.google.protobuf.ByteString
      getIndexFlagBytes();

  /**
   * <code>string dimensionFlag = 19;</code>
   */
  java.lang.String getDimensionFlag();
  /**
   * <code>string dimensionFlag = 19;</code>
   */
  com.google.protobuf.ByteString
      getDimensionFlagBytes();
}
