// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ForBo.proto

package com.xforceplus.ultraman.oqsengine.meta.proto.test;

public interface ModuleUpOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ModuleUp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 传入的模块id.
   * </pre>
   *
   * <code>string moduleId = 1;</code>
   */
  java.lang.String getModuleId();
  /**
   * <pre>
   * 传入的模块id.
   * </pre>
   *
   * <code>string moduleId = 1;</code>
   */
  com.google.protobuf.ByteString
      getModuleIdBytes();

  /**
   * <pre>
   * 模块版本.
   * </pre>
   *
   * <code>string moduleVersion = 2;</code>
   */
  java.lang.String getModuleVersion();
  /**
   * <pre>
   * 模块版本.
   * </pre>
   *
   * <code>string moduleVersion = 2;</code>
   */
  com.google.protobuf.ByteString
      getModuleVersionBytes();

  /**
   * <pre>
   * 当前授权信息.
   * </pre>
   *
   * <code>repeated .Authorization authorization = 3;</code>
   */
  java.util.List<com.xforceplus.ultraman.oqsengine.meta.proto.test.Authorization> 
      getAuthorizationList();
  /**
   * <pre>
   * 当前授权信息.
   * </pre>
   *
   * <code>repeated .Authorization authorization = 3;</code>
   */
  com.xforceplus.ultraman.oqsengine.meta.proto.test.Authorization getAuthorization(int index);
  /**
   * <pre>
   * 当前授权信息.
   * </pre>
   *
   * <code>repeated .Authorization authorization = 3;</code>
   */
  int getAuthorizationCount();
  /**
   * <pre>
   * 当前授权信息.
   * </pre>
   *
   * <code>repeated .Authorization authorization = 3;</code>
   */
  java.util.List<? extends com.xforceplus.ultraman.oqsengine.meta.proto.test.AuthorizationOrBuilder> 
      getAuthorizationOrBuilderList();
  /**
   * <pre>
   * 当前授权信息.
   * </pre>
   *
   * <code>repeated .Authorization authorization = 3;</code>
   */
  com.xforceplus.ultraman.oqsengine.meta.proto.test.AuthorizationOrBuilder getAuthorizationOrBuilder(
      int index);
}
