// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ForBo.proto

package com.xforceplus.ultraman.oqsengine.meta.proto.test;

/**
 * Protobuf type {@code Relation}
 */
public  final class Relation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Relation)
    RelationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Relation.newBuilder() to construct.
  private Relation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Relation() {
    id_ = "";
    relationType_ = "";
    identity_ = false;
    boId_ = "";
    joinBoId_ = "";
    relName_ = "";
    boField_ = 0L;
    joinField_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Relation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            relationType_ = s;
            break;
          }
          case 24: {

            identity_ = input.readBool();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            boId_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            joinBoId_ = s;
            break;
          }
          case 50: {
            com.xforceplus.ultraman.oqsengine.meta.proto.test.Field.Builder subBuilder = null;
            if (field_ != null) {
              subBuilder = field_.toBuilder();
            }
            field_ = input.readMessage(com.xforceplus.ultraman.oqsengine.meta.proto.test.Field.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(field_);
              field_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            relName_ = s;
            break;
          }
          case 64: {

            boField_ = input.readInt64();
            break;
          }
          case 72: {

            joinField_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xforceplus.ultraman.oqsengine.meta.proto.test.MetadataResourceProto.internal_static_Relation_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xforceplus.ultraman.oqsengine.meta.proto.test.MetadataResourceProto.internal_static_Relation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation.class, com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RELATIONTYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object relationType_;
  /**
   * <code>string relationType = 2;</code>
   */
  public java.lang.String getRelationType() {
    java.lang.Object ref = relationType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      relationType_ = s;
      return s;
    }
  }
  /**
   * <code>string relationType = 2;</code>
   */
  public com.google.protobuf.ByteString
      getRelationTypeBytes() {
    java.lang.Object ref = relationType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      relationType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IDENTITY_FIELD_NUMBER = 3;
  private boolean identity_;
  /**
   * <code>bool identity = 3;</code>
   */
  public boolean getIdentity() {
    return identity_;
  }

  public static final int BOID_FIELD_NUMBER = 4;
  private volatile java.lang.Object boId_;
  /**
   * <code>string boId = 4;</code>
   */
  public java.lang.String getBoId() {
    java.lang.Object ref = boId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      boId_ = s;
      return s;
    }
  }
  /**
   * <code>string boId = 4;</code>
   */
  public com.google.protobuf.ByteString
      getBoIdBytes() {
    java.lang.Object ref = boId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      boId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JOINBOID_FIELD_NUMBER = 5;
  private volatile java.lang.Object joinBoId_;
  /**
   * <code>string joinBoId = 5;</code>
   */
  public java.lang.String getJoinBoId() {
    java.lang.Object ref = joinBoId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      joinBoId_ = s;
      return s;
    }
  }
  /**
   * <code>string joinBoId = 5;</code>
   */
  public com.google.protobuf.ByteString
      getJoinBoIdBytes() {
    java.lang.Object ref = joinBoId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      joinBoId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELD_FIELD_NUMBER = 6;
  private com.xforceplus.ultraman.oqsengine.meta.proto.test.Field field_;
  /**
   * <pre>
   *ManyToOne 和 OneToOne 将joinBo的joinCode.id来命名字段，如果该id等于joinBoId，则将boCode.id来命名字段
   * </pre>
   *
   * <code>.Field field = 6;</code>
   */
  public boolean hasField() {
    return field_ != null;
  }
  /**
   * <pre>
   *ManyToOne 和 OneToOne 将joinBo的joinCode.id来命名字段，如果该id等于joinBoId，则将boCode.id来命名字段
   * </pre>
   *
   * <code>.Field field = 6;</code>
   */
  public com.xforceplus.ultraman.oqsengine.meta.proto.test.Field getField() {
    return field_ == null ? com.xforceplus.ultraman.oqsengine.meta.proto.test.Field.getDefaultInstance() : field_;
  }
  /**
   * <pre>
   *ManyToOne 和 OneToOne 将joinBo的joinCode.id来命名字段，如果该id等于joinBoId，则将boCode.id来命名字段
   * </pre>
   *
   * <code>.Field field = 6;</code>
   */
  public com.xforceplus.ultraman.oqsengine.meta.proto.test.FieldOrBuilder getFieldOrBuilder() {
    return getField();
  }

  public static final int RELNAME_FIELD_NUMBER = 7;
  private volatile java.lang.Object relName_;
  /**
   * <code>string relName = 7;</code>
   */
  public java.lang.String getRelName() {
    java.lang.Object ref = relName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      relName_ = s;
      return s;
    }
  }
  /**
   * <code>string relName = 7;</code>
   */
  public com.google.protobuf.ByteString
      getRelNameBytes() {
    java.lang.Object ref = relName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      relName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BOFIELD_FIELD_NUMBER = 8;
  private long boField_;
  /**
   * <code>int64 boField = 8;</code>
   */
  public long getBoField() {
    return boField_;
  }

  public static final int JOINFIELD_FIELD_NUMBER = 9;
  private long joinField_;
  /**
   * <code>int64 joinField = 9;</code>
   */
  public long getJoinField() {
    return joinField_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getRelationTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, relationType_);
    }
    if (identity_ != false) {
      output.writeBool(3, identity_);
    }
    if (!getBoIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, boId_);
    }
    if (!getJoinBoIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, joinBoId_);
    }
    if (field_ != null) {
      output.writeMessage(6, getField());
    }
    if (!getRelNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, relName_);
    }
    if (boField_ != 0L) {
      output.writeInt64(8, boField_);
    }
    if (joinField_ != 0L) {
      output.writeInt64(9, joinField_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getRelationTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, relationType_);
    }
    if (identity_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, identity_);
    }
    if (!getBoIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, boId_);
    }
    if (!getJoinBoIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, joinBoId_);
    }
    if (field_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getField());
    }
    if (!getRelNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, relName_);
    }
    if (boField_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, boField_);
    }
    if (joinField_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, joinField_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation)) {
      return super.equals(obj);
    }
    com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation other = (com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation) obj;

    boolean result = true;
    result = result && getId()
        .equals(other.getId());
    result = result && getRelationType()
        .equals(other.getRelationType());
    result = result && (getIdentity()
        == other.getIdentity());
    result = result && getBoId()
        .equals(other.getBoId());
    result = result && getJoinBoId()
        .equals(other.getJoinBoId());
    result = result && (hasField() == other.hasField());
    if (hasField()) {
      result = result && getField()
          .equals(other.getField());
    }
    result = result && getRelName()
        .equals(other.getRelName());
    result = result && (getBoField()
        == other.getBoField());
    result = result && (getJoinField()
        == other.getJoinField());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + RELATIONTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getRelationType().hashCode();
    hash = (37 * hash) + IDENTITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIdentity());
    hash = (37 * hash) + BOID_FIELD_NUMBER;
    hash = (53 * hash) + getBoId().hashCode();
    hash = (37 * hash) + JOINBOID_FIELD_NUMBER;
    hash = (53 * hash) + getJoinBoId().hashCode();
    if (hasField()) {
      hash = (37 * hash) + FIELD_FIELD_NUMBER;
      hash = (53 * hash) + getField().hashCode();
    }
    hash = (37 * hash) + RELNAME_FIELD_NUMBER;
    hash = (53 * hash) + getRelName().hashCode();
    hash = (37 * hash) + BOFIELD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBoField());
    hash = (37 * hash) + JOINFIELD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getJoinField());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Relation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Relation)
      com.xforceplus.ultraman.oqsengine.meta.proto.test.RelationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xforceplus.ultraman.oqsengine.meta.proto.test.MetadataResourceProto.internal_static_Relation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xforceplus.ultraman.oqsengine.meta.proto.test.MetadataResourceProto.internal_static_Relation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation.class, com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation.Builder.class);
    }

    // Construct using com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = "";

      relationType_ = "";

      identity_ = false;

      boId_ = "";

      joinBoId_ = "";

      if (fieldBuilder_ == null) {
        field_ = null;
      } else {
        field_ = null;
        fieldBuilder_ = null;
      }
      relName_ = "";

      boField_ = 0L;

      joinField_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xforceplus.ultraman.oqsengine.meta.proto.test.MetadataResourceProto.internal_static_Relation_descriptor;
    }

    public com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation getDefaultInstanceForType() {
      return com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation.getDefaultInstance();
    }

    public com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation build() {
      com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation buildPartial() {
      com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation result = new com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation(this);
      result.id_ = id_;
      result.relationType_ = relationType_;
      result.identity_ = identity_;
      result.boId_ = boId_;
      result.joinBoId_ = joinBoId_;
      if (fieldBuilder_ == null) {
        result.field_ = field_;
      } else {
        result.field_ = fieldBuilder_.build();
      }
      result.relName_ = relName_;
      result.boField_ = boField_;
      result.joinField_ = joinField_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation) {
        return mergeFrom((com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation other) {
      if (other == com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getRelationType().isEmpty()) {
        relationType_ = other.relationType_;
        onChanged();
      }
      if (other.getIdentity() != false) {
        setIdentity(other.getIdentity());
      }
      if (!other.getBoId().isEmpty()) {
        boId_ = other.boId_;
        onChanged();
      }
      if (!other.getJoinBoId().isEmpty()) {
        joinBoId_ = other.joinBoId_;
        onChanged();
      }
      if (other.hasField()) {
        mergeField(other.getField());
      }
      if (!other.getRelName().isEmpty()) {
        relName_ = other.relName_;
        onChanged();
      }
      if (other.getBoField() != 0L) {
        setBoField(other.getBoField());
      }
      if (other.getJoinField() != 0L) {
        setJoinField(other.getJoinField());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object relationType_ = "";
    /**
     * <code>string relationType = 2;</code>
     */
    public java.lang.String getRelationType() {
      java.lang.Object ref = relationType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        relationType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string relationType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRelationTypeBytes() {
      java.lang.Object ref = relationType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        relationType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string relationType = 2;</code>
     */
    public Builder setRelationType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      relationType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string relationType = 2;</code>
     */
    public Builder clearRelationType() {
      
      relationType_ = getDefaultInstance().getRelationType();
      onChanged();
      return this;
    }
    /**
     * <code>string relationType = 2;</code>
     */
    public Builder setRelationTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      relationType_ = value;
      onChanged();
      return this;
    }

    private boolean identity_ ;
    /**
     * <code>bool identity = 3;</code>
     */
    public boolean getIdentity() {
      return identity_;
    }
    /**
     * <code>bool identity = 3;</code>
     */
    public Builder setIdentity(boolean value) {
      
      identity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool identity = 3;</code>
     */
    public Builder clearIdentity() {
      
      identity_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object boId_ = "";
    /**
     * <code>string boId = 4;</code>
     */
    public java.lang.String getBoId() {
      java.lang.Object ref = boId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        boId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string boId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBoIdBytes() {
      java.lang.Object ref = boId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        boId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string boId = 4;</code>
     */
    public Builder setBoId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      boId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string boId = 4;</code>
     */
    public Builder clearBoId() {
      
      boId_ = getDefaultInstance().getBoId();
      onChanged();
      return this;
    }
    /**
     * <code>string boId = 4;</code>
     */
    public Builder setBoIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      boId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object joinBoId_ = "";
    /**
     * <code>string joinBoId = 5;</code>
     */
    public java.lang.String getJoinBoId() {
      java.lang.Object ref = joinBoId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        joinBoId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string joinBoId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getJoinBoIdBytes() {
      java.lang.Object ref = joinBoId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        joinBoId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string joinBoId = 5;</code>
     */
    public Builder setJoinBoId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      joinBoId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string joinBoId = 5;</code>
     */
    public Builder clearJoinBoId() {
      
      joinBoId_ = getDefaultInstance().getJoinBoId();
      onChanged();
      return this;
    }
    /**
     * <code>string joinBoId = 5;</code>
     */
    public Builder setJoinBoIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      joinBoId_ = value;
      onChanged();
      return this;
    }

    private com.xforceplus.ultraman.oqsengine.meta.proto.test.Field field_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xforceplus.ultraman.oqsengine.meta.proto.test.Field, com.xforceplus.ultraman.oqsengine.meta.proto.test.Field.Builder, com.xforceplus.ultraman.oqsengine.meta.proto.test.FieldOrBuilder> fieldBuilder_;
    /**
     * <pre>
     *ManyToOne 和 OneToOne 将joinBo的joinCode.id来命名字段，如果该id等于joinBoId，则将boCode.id来命名字段
     * </pre>
     *
     * <code>.Field field = 6;</code>
     */
    public boolean hasField() {
      return fieldBuilder_ != null || field_ != null;
    }
    /**
     * <pre>
     *ManyToOne 和 OneToOne 将joinBo的joinCode.id来命名字段，如果该id等于joinBoId，则将boCode.id来命名字段
     * </pre>
     *
     * <code>.Field field = 6;</code>
     */
    public com.xforceplus.ultraman.oqsengine.meta.proto.test.Field getField() {
      if (fieldBuilder_ == null) {
        return field_ == null ? com.xforceplus.ultraman.oqsengine.meta.proto.test.Field.getDefaultInstance() : field_;
      } else {
        return fieldBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *ManyToOne 和 OneToOne 将joinBo的joinCode.id来命名字段，如果该id等于joinBoId，则将boCode.id来命名字段
     * </pre>
     *
     * <code>.Field field = 6;</code>
     */
    public Builder setField(com.xforceplus.ultraman.oqsengine.meta.proto.test.Field value) {
      if (fieldBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        field_ = value;
        onChanged();
      } else {
        fieldBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *ManyToOne 和 OneToOne 将joinBo的joinCode.id来命名字段，如果该id等于joinBoId，则将boCode.id来命名字段
     * </pre>
     *
     * <code>.Field field = 6;</code>
     */
    public Builder setField(
        com.xforceplus.ultraman.oqsengine.meta.proto.test.Field.Builder builderForValue) {
      if (fieldBuilder_ == null) {
        field_ = builderForValue.build();
        onChanged();
      } else {
        fieldBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *ManyToOne 和 OneToOne 将joinBo的joinCode.id来命名字段，如果该id等于joinBoId，则将boCode.id来命名字段
     * </pre>
     *
     * <code>.Field field = 6;</code>
     */
    public Builder mergeField(com.xforceplus.ultraman.oqsengine.meta.proto.test.Field value) {
      if (fieldBuilder_ == null) {
        if (field_ != null) {
          field_ =
            com.xforceplus.ultraman.oqsengine.meta.proto.test.Field.newBuilder(field_).mergeFrom(value).buildPartial();
        } else {
          field_ = value;
        }
        onChanged();
      } else {
        fieldBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *ManyToOne 和 OneToOne 将joinBo的joinCode.id来命名字段，如果该id等于joinBoId，则将boCode.id来命名字段
     * </pre>
     *
     * <code>.Field field = 6;</code>
     */
    public Builder clearField() {
      if (fieldBuilder_ == null) {
        field_ = null;
        onChanged();
      } else {
        field_ = null;
        fieldBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *ManyToOne 和 OneToOne 将joinBo的joinCode.id来命名字段，如果该id等于joinBoId，则将boCode.id来命名字段
     * </pre>
     *
     * <code>.Field field = 6;</code>
     */
    public com.xforceplus.ultraman.oqsengine.meta.proto.test.Field.Builder getFieldBuilder() {
      
      onChanged();
      return getFieldFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *ManyToOne 和 OneToOne 将joinBo的joinCode.id来命名字段，如果该id等于joinBoId，则将boCode.id来命名字段
     * </pre>
     *
     * <code>.Field field = 6;</code>
     */
    public com.xforceplus.ultraman.oqsengine.meta.proto.test.FieldOrBuilder getFieldOrBuilder() {
      if (fieldBuilder_ != null) {
        return fieldBuilder_.getMessageOrBuilder();
      } else {
        return field_ == null ?
            com.xforceplus.ultraman.oqsengine.meta.proto.test.Field.getDefaultInstance() : field_;
      }
    }
    /**
     * <pre>
     *ManyToOne 和 OneToOne 将joinBo的joinCode.id来命名字段，如果该id等于joinBoId，则将boCode.id来命名字段
     * </pre>
     *
     * <code>.Field field = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xforceplus.ultraman.oqsengine.meta.proto.test.Field, com.xforceplus.ultraman.oqsengine.meta.proto.test.Field.Builder, com.xforceplus.ultraman.oqsengine.meta.proto.test.FieldOrBuilder> 
        getFieldFieldBuilder() {
      if (fieldBuilder_ == null) {
        fieldBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xforceplus.ultraman.oqsengine.meta.proto.test.Field, com.xforceplus.ultraman.oqsengine.meta.proto.test.Field.Builder, com.xforceplus.ultraman.oqsengine.meta.proto.test.FieldOrBuilder>(
                getField(),
                getParentForChildren(),
                isClean());
        field_ = null;
      }
      return fieldBuilder_;
    }

    private java.lang.Object relName_ = "";
    /**
     * <code>string relName = 7;</code>
     */
    public java.lang.String getRelName() {
      java.lang.Object ref = relName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        relName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string relName = 7;</code>
     */
    public com.google.protobuf.ByteString
        getRelNameBytes() {
      java.lang.Object ref = relName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        relName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string relName = 7;</code>
     */
    public Builder setRelName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      relName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string relName = 7;</code>
     */
    public Builder clearRelName() {
      
      relName_ = getDefaultInstance().getRelName();
      onChanged();
      return this;
    }
    /**
     * <code>string relName = 7;</code>
     */
    public Builder setRelNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      relName_ = value;
      onChanged();
      return this;
    }

    private long boField_ ;
    /**
     * <code>int64 boField = 8;</code>
     */
    public long getBoField() {
      return boField_;
    }
    /**
     * <code>int64 boField = 8;</code>
     */
    public Builder setBoField(long value) {
      
      boField_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 boField = 8;</code>
     */
    public Builder clearBoField() {
      
      boField_ = 0L;
      onChanged();
      return this;
    }

    private long joinField_ ;
    /**
     * <code>int64 joinField = 9;</code>
     */
    public long getJoinField() {
      return joinField_;
    }
    /**
     * <code>int64 joinField = 9;</code>
     */
    public Builder setJoinField(long value) {
      
      joinField_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 joinField = 9;</code>
     */
    public Builder clearJoinField() {
      
      joinField_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Relation)
  }

  // @@protoc_insertion_point(class_scope:Relation)
  private static final com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation();
  }

  public static com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Relation>
      PARSER = new com.google.protobuf.AbstractParser<Relation>() {
    public Relation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Relation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Relation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Relation> getParserForType() {
    return PARSER;
  }

  public com.xforceplus.ultraman.oqsengine.meta.proto.test.Relation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

