// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ForBo.proto

package com.xforceplus.ultraman.oqsengine.meta.proto.test;

public interface RelationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Relation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string relationType = 2;</code>
   */
  java.lang.String getRelationType();
  /**
   * <code>string relationType = 2;</code>
   */
  com.google.protobuf.ByteString
      getRelationTypeBytes();

  /**
   * <code>bool identity = 3;</code>
   */
  boolean getIdentity();

  /**
   * <code>string boId = 4;</code>
   */
  java.lang.String getBoId();
  /**
   * <code>string boId = 4;</code>
   */
  com.google.protobuf.ByteString
      getBoIdBytes();

  /**
   * <code>string joinBoId = 5;</code>
   */
  java.lang.String getJoinBoId();
  /**
   * <code>string joinBoId = 5;</code>
   */
  com.google.protobuf.ByteString
      getJoinBoIdBytes();

  /**
   * <pre>
   *ManyToOne 和 OneToOne 将joinBo的joinCode.id来命名字段，如果该id等于joinBoId，则将boCode.id来命名字段
   * </pre>
   *
   * <code>.Field field = 6;</code>
   */
  boolean hasField();
  /**
   * <pre>
   *ManyToOne 和 OneToOne 将joinBo的joinCode.id来命名字段，如果该id等于joinBoId，则将boCode.id来命名字段
   * </pre>
   *
   * <code>.Field field = 6;</code>
   */
  com.xforceplus.ultraman.oqsengine.meta.proto.test.Field getField();
  /**
   * <pre>
   *ManyToOne 和 OneToOne 将joinBo的joinCode.id来命名字段，如果该id等于joinBoId，则将boCode.id来命名字段
   * </pre>
   *
   * <code>.Field field = 6;</code>
   */
  com.xforceplus.ultraman.oqsengine.meta.proto.test.FieldOrBuilder getFieldOrBuilder();

  /**
   * <code>string relName = 7;</code>
   */
  java.lang.String getRelName();
  /**
   * <code>string relName = 7;</code>
   */
  com.google.protobuf.ByteString
      getRelNameBytes();

  /**
   * <code>int64 boField = 8;</code>
   */
  long getBoField();

  /**
   * <code>int64 joinField = 9;</code>
   */
  long getJoinField();
}
