use oqsengine;

create TABLE changeversion (
  vid BIGINT(20) NOT NULL AUTO_INCREMENT,
  id BIGINT(20) DEFAULT NULL,
  user VARCHAR(255) DEFAULT NULL,
  comment VARCHAR(255) DEFAULT NULL,
  timestamp BIGINT(20) DEFAULT NULL,
  version BIGINT(20) DEFAULT NULL,
  count BIGINT(20) DEFAULT NULL,
  source BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (vid)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

create TABLE changesnapshot (
  sid BIGINT(20) NOT NULL AUTO_INCREMENT,
  id BIGINT(20) DEFAULT NULL,
  entity BIGINT(20) DEFAULT NULL,
  changes JSON DEFAULT NULL,
  reference JSON DEFAULT NULL,
  version BIGINT(20) DEFAULT NULL,
  create_time VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (sid)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;


create TABLE changelog (
  cid BIGINT(20) NOT NULL AUTO_INCREMENT,
  id BIGINT(20) DEFAULT NULL,
  entity BIGINT(20) DEFAULT NULL,
  changes JSON DEFAULT NULL,
  reference JSON DEFAULT NULL,
  version BIGINT(20) DEFAULT NULL,
  create_time VARCHAR(255) DEFAULT NULL,
  comment VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (cid)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;