
// Generated by Akka gRPC. DO NOT EDIT.
package com.xforceplus.ultraman.oqsengine.sdk;


import akka.grpc.javadsl.SingleResponseRequestBuilder;


public abstract class EntityServiceClientPowerApi {
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer begin(com.xforceplus.ultraman.oqsengine.sdk.TransactionUp) if possible.
     */
    
      public SingleResponseRequestBuilder<TransactionUp, OperationResult> begin()

    {
        throw new UnsupportedOperationException();
    }

    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer build(com.xforceplus.ultraman.oqsengine.sdk.EntityUp) if possible.
     */

      public SingleResponseRequestBuilder<EntityUp, OperationResult> build()

    {
        throw new UnsupportedOperationException();
    }

    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer replace(com.xforceplus.ultraman.oqsengine.sdk.EntityUp) if possible.
     */

      public SingleResponseRequestBuilder<EntityUp, OperationResult> replace()

    {
        throw new UnsupportedOperationException();
    }

    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer remove(com.xforceplus.ultraman.oqsengine.sdk.EntityUp) if possible.
     */

      public SingleResponseRequestBuilder<EntityUp, OperationResult> remove()

    {
        throw new UnsupportedOperationException();
    }

    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer selectOne(com.xforceplus.ultraman.oqsengine.sdk.EntityUp) if possible.
     */

      public SingleResponseRequestBuilder<EntityUp, OperationResult> selectOne()

    {
        throw new UnsupportedOperationException();
    }

    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer selectByConditions(com.xforceplus.ultraman.oqsengine.sdk.SelectByCondition) if possible.
     */

      public SingleResponseRequestBuilder<SelectByCondition, OperationResult> selectByConditions()

    {
        throw new UnsupportedOperationException();
    }

    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer commit(com.xforceplus.ultraman.oqsengine.sdk.TransactionUp) if possible.
     */

      public SingleResponseRequestBuilder<TransactionUp, OperationResult> commit()

    {
        throw new UnsupportedOperationException();
    }

    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer rollBack(com.xforceplus.ultraman.oqsengine.sdk.TransactionUp) if possible.
     */

      public SingleResponseRequestBuilder<TransactionUp, OperationResult> rollBack()

    {
        throw new UnsupportedOperationException();
    }
  
}
