
// Generated by Akka gRPC. DO NOT EDIT.
package com.xforceplus.ultraman.oqsengine.sdk;


import akka.grpc.javadsl.SingleResponseRequestBuilder;


public abstract class EntityServiceClientPowerApi {
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer begin(com.xforceplus.ultraman.oqsengine.sdk.TransactionUp) if possible.
     */
    
      public SingleResponseRequestBuilder<com.xforceplus.ultraman.oqsengine.sdk.TransactionUp, com.xforceplus.ultraman.oqsengine.sdk.OperationResult> begin()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer build(com.xforceplus.ultraman.oqsengine.sdk.EntityUp) if possible.
     */
    
      public SingleResponseRequestBuilder<com.xforceplus.ultraman.oqsengine.sdk.EntityUp, com.xforceplus.ultraman.oqsengine.sdk.OperationResult> build()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer replace(com.xforceplus.ultraman.oqsengine.sdk.EntityUp) if possible.
     */
    
      public SingleResponseRequestBuilder<com.xforceplus.ultraman.oqsengine.sdk.EntityUp, com.xforceplus.ultraman.oqsengine.sdk.OperationResult> replace()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer replaceByCondition(com.xforceplus.ultraman.oqsengine.sdk.SelectByCondition) if possible.
     */
    
      public SingleResponseRequestBuilder<com.xforceplus.ultraman.oqsengine.sdk.SelectByCondition, com.xforceplus.ultraman.oqsengine.sdk.OperationResult> replaceByCondition()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer remove(com.xforceplus.ultraman.oqsengine.sdk.EntityUp) if possible.
     */
    
      public SingleResponseRequestBuilder<com.xforceplus.ultraman.oqsengine.sdk.EntityUp, com.xforceplus.ultraman.oqsengine.sdk.OperationResult> remove()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer selectOne(com.xforceplus.ultraman.oqsengine.sdk.EntityUp) if possible.
     */
    
      public SingleResponseRequestBuilder<com.xforceplus.ultraman.oqsengine.sdk.EntityUp, com.xforceplus.ultraman.oqsengine.sdk.OperationResult> selectOne()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer selectByConditions(com.xforceplus.ultraman.oqsengine.sdk.SelectByCondition) if possible.
     */
    
      public SingleResponseRequestBuilder<com.xforceplus.ultraman.oqsengine.sdk.SelectByCondition, com.xforceplus.ultraman.oqsengine.sdk.OperationResult> selectByConditions()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer commit(com.xforceplus.ultraman.oqsengine.sdk.TransactionUp) if possible.
     */
    
      public SingleResponseRequestBuilder<com.xforceplus.ultraman.oqsengine.sdk.TransactionUp, com.xforceplus.ultraman.oqsengine.sdk.OperationResult> commit()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer rollBack(com.xforceplus.ultraman.oqsengine.sdk.TransactionUp) if possible.
     */
    
      public SingleResponseRequestBuilder<com.xforceplus.ultraman.oqsengine.sdk.TransactionUp, com.xforceplus.ultraman.oqsengine.sdk.OperationResult> rollBack()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
}
