// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package com.xforceplus.ultraman.oqsengine.sdk;

/**
 * Protobuf type {@code RelationUp}
 */
public  final class RelationUp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RelationUp)
    RelationUpOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RelationUp.newBuilder() to construct.
  private RelationUp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RelationUp() {
    name_ = "";
    relationType_ = "";
    identity_ = false;
    relatedEntityClassId_ = 0L;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RelationUp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            relationType_ = s;
            break;
          }
          case 24: {

            identity_ = input.readBool();
            break;
          }
          case 34: {
            FieldUp.Builder subBuilder = null;
            if (entityField_ != null) {
              subBuilder = entityField_.toBuilder();
            }
            entityField_ = input.readMessage(FieldUp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(entityField_);
              entityField_ = subBuilder.buildPartial();
            }

            break;
          }
          case 40: {

            relatedEntityClassId_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return EntityResourceProto.internal_static_RelationUp_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return EntityResourceProto.internal_static_RelationUp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            RelationUp.class, RelationUp.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile Object name_;
  /**
   * <code>string name = 1;</code>
   */
  public String getName() {
    Object ref = name_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    Object ref = name_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RELATIONTYPE_FIELD_NUMBER = 2;
  private volatile Object relationType_;
  /**
   * <code>string relationType = 2;</code>
   */
  public String getRelationType() {
    Object ref = relationType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      relationType_ = s;
      return s;
    }
  }
  /**
   * <code>string relationType = 2;</code>
   */
  public com.google.protobuf.ByteString
      getRelationTypeBytes() {
    Object ref = relationType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      relationType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IDENTITY_FIELD_NUMBER = 3;
  private boolean identity_;
  /**
   * <code>bool identity = 3;</code>
   */
  public boolean getIdentity() {
    return identity_;
  }

  public static final int ENTITYFIELD_FIELD_NUMBER = 4;
  private FieldUp entityField_;
  /**
   * <code>.FieldUp entityField = 4;</code>
   */
  public boolean hasEntityField() {
    return entityField_ != null;
  }
  /**
   * <code>.FieldUp entityField = 4;</code>
   */
  public FieldUp getEntityField() {
    return entityField_ == null ? FieldUp.getDefaultInstance() : entityField_;
  }
  /**
   * <code>.FieldUp entityField = 4;</code>
   */
  public FieldUpOrBuilder getEntityFieldOrBuilder() {
    return getEntityField();
  }

  public static final int RELATEDENTITYCLASSID_FIELD_NUMBER = 5;
  private long relatedEntityClassId_;
  /**
   * <code>int64 relatedEntityClassId = 5;</code>
   */
  public long getRelatedEntityClassId() {
    return relatedEntityClassId_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!getRelationTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, relationType_);
    }
    if (identity_ != false) {
      output.writeBool(3, identity_);
    }
    if (entityField_ != null) {
      output.writeMessage(4, getEntityField());
    }
    if (relatedEntityClassId_ != 0L) {
      output.writeInt64(5, relatedEntityClassId_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!getRelationTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, relationType_);
    }
    if (identity_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, identity_);
    }
    if (entityField_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getEntityField());
    }
    if (relatedEntityClassId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, relatedEntityClassId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof RelationUp)) {
      return super.equals(obj);
    }
    RelationUp other = (RelationUp) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && getRelationType()
        .equals(other.getRelationType());
    result = result && (getIdentity()
        == other.getIdentity());
    result = result && (hasEntityField() == other.hasEntityField());
    if (hasEntityField()) {
      result = result && getEntityField()
          .equals(other.getEntityField());
    }
    result = result && (getRelatedEntityClassId()
        == other.getRelatedEntityClassId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + RELATIONTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getRelationType().hashCode();
    hash = (37 * hash) + IDENTITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIdentity());
    if (hasEntityField()) {
      hash = (37 * hash) + ENTITYFIELD_FIELD_NUMBER;
      hash = (53 * hash) + getEntityField().hashCode();
    }
    hash = (37 * hash) + RELATEDENTITYCLASSID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRelatedEntityClassId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static RelationUp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RelationUp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RelationUp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RelationUp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RelationUp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RelationUp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RelationUp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RelationUp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static RelationUp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static RelationUp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static RelationUp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RelationUp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(RelationUp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RelationUp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RelationUp)
      RelationUpOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EntityResourceProto.internal_static_RelationUp_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EntityResourceProto.internal_static_RelationUp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RelationUp.class, RelationUp.Builder.class);
    }

    // Construct using com.xforceplus.ultraman.oqsengine.sdk.RelationUp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      name_ = "";

      relationType_ = "";

      identity_ = false;

      if (entityFieldBuilder_ == null) {
        entityField_ = null;
      } else {
        entityField_ = null;
        entityFieldBuilder_ = null;
      }
      relatedEntityClassId_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return EntityResourceProto.internal_static_RelationUp_descriptor;
    }

    public RelationUp getDefaultInstanceForType() {
      return RelationUp.getDefaultInstance();
    }

    public RelationUp build() {
      RelationUp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public RelationUp buildPartial() {
      RelationUp result = new RelationUp(this);
      result.name_ = name_;
      result.relationType_ = relationType_;
      result.identity_ = identity_;
      if (entityFieldBuilder_ == null) {
        result.entityField_ = entityField_;
      } else {
        result.entityField_ = entityFieldBuilder_.build();
      }
      result.relatedEntityClassId_ = relatedEntityClassId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof RelationUp) {
        return mergeFrom((RelationUp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(RelationUp other) {
      if (other == RelationUp.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getRelationType().isEmpty()) {
        relationType_ = other.relationType_;
        onChanged();
      }
      if (other.getIdentity() != false) {
        setIdentity(other.getIdentity());
      }
      if (other.hasEntityField()) {
        mergeEntityField(other.getEntityField());
      }
      if (other.getRelatedEntityClassId() != 0L) {
        setRelatedEntityClassId(other.getRelatedEntityClassId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      RelationUp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (RelationUp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object name_ = "";
    /**
     * <code>string name = 1;</code>
     */
    public String getName() {
      Object ref = name_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder clearName() {

      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      name_ = value;
      onChanged();
      return this;
    }

    private Object relationType_ = "";
    /**
     * <code>string relationType = 2;</code>
     */
    public String getRelationType() {
      Object ref = relationType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        relationType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string relationType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRelationTypeBytes() {
      Object ref = relationType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        relationType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string relationType = 2;</code>
     */
    public Builder setRelationType(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      relationType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string relationType = 2;</code>
     */
    public Builder clearRelationType() {

      relationType_ = getDefaultInstance().getRelationType();
      onChanged();
      return this;
    }
    /**
     * <code>string relationType = 2;</code>
     */
    public Builder setRelationTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      relationType_ = value;
      onChanged();
      return this;
    }

    private boolean identity_ ;
    /**
     * <code>bool identity = 3;</code>
     */
    public boolean getIdentity() {
      return identity_;
    }
    /**
     * <code>bool identity = 3;</code>
     */
    public Builder setIdentity(boolean value) {

      identity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool identity = 3;</code>
     */
    public Builder clearIdentity() {

      identity_ = false;
      onChanged();
      return this;
    }

    private FieldUp entityField_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        FieldUp, FieldUp.Builder, FieldUpOrBuilder> entityFieldBuilder_;
    /**
     * <code>.FieldUp entityField = 4;</code>
     */
    public boolean hasEntityField() {
      return entityFieldBuilder_ != null || entityField_ != null;
    }
    /**
     * <code>.FieldUp entityField = 4;</code>
     */
    public FieldUp getEntityField() {
      if (entityFieldBuilder_ == null) {
        return entityField_ == null ? FieldUp.getDefaultInstance() : entityField_;
      } else {
        return entityFieldBuilder_.getMessage();
      }
    }
    /**
     * <code>.FieldUp entityField = 4;</code>
     */
    public Builder setEntityField(FieldUp value) {
      if (entityFieldBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        entityField_ = value;
        onChanged();
      } else {
        entityFieldBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.FieldUp entityField = 4;</code>
     */
    public Builder setEntityField(
        FieldUp.Builder builderForValue) {
      if (entityFieldBuilder_ == null) {
        entityField_ = builderForValue.build();
        onChanged();
      } else {
        entityFieldBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.FieldUp entityField = 4;</code>
     */
    public Builder mergeEntityField(FieldUp value) {
      if (entityFieldBuilder_ == null) {
        if (entityField_ != null) {
          entityField_ =
            FieldUp.newBuilder(entityField_).mergeFrom(value).buildPartial();
        } else {
          entityField_ = value;
        }
        onChanged();
      } else {
        entityFieldBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.FieldUp entityField = 4;</code>
     */
    public Builder clearEntityField() {
      if (entityFieldBuilder_ == null) {
        entityField_ = null;
        onChanged();
      } else {
        entityField_ = null;
        entityFieldBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.FieldUp entityField = 4;</code>
     */
    public FieldUp.Builder getEntityFieldBuilder() {

      onChanged();
      return getEntityFieldFieldBuilder().getBuilder();
    }
    /**
     * <code>.FieldUp entityField = 4;</code>
     */
    public FieldUpOrBuilder getEntityFieldOrBuilder() {
      if (entityFieldBuilder_ != null) {
        return entityFieldBuilder_.getMessageOrBuilder();
      } else {
        return entityField_ == null ?
            FieldUp.getDefaultInstance() : entityField_;
      }
    }
    /**
     * <code>.FieldUp entityField = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        FieldUp, FieldUp.Builder, FieldUpOrBuilder>
        getEntityFieldFieldBuilder() {
      if (entityFieldBuilder_ == null) {
        entityFieldBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            FieldUp, FieldUp.Builder, FieldUpOrBuilder>(
                getEntityField(),
                getParentForChildren(),
                isClean());
        entityField_ = null;
      }
      return entityFieldBuilder_;
    }

    private long relatedEntityClassId_ ;
    /**
     * <code>int64 relatedEntityClassId = 5;</code>
     */
    public long getRelatedEntityClassId() {
      return relatedEntityClassId_;
    }
    /**
     * <code>int64 relatedEntityClassId = 5;</code>
     */
    public Builder setRelatedEntityClassId(long value) {

      relatedEntityClassId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 relatedEntityClassId = 5;</code>
     */
    public Builder clearRelatedEntityClassId() {

      relatedEntityClassId_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RelationUp)
  }

  // @@protoc_insertion_point(class_scope:RelationUp)
  private static final RelationUp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RelationUp();
  }

  public static RelationUp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RelationUp>
      PARSER = new com.google.protobuf.AbstractParser<RelationUp>() {
    public RelationUp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RelationUp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RelationUp> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<RelationUp> getParserForType() {
    return PARSER;
  }

  public RelationUp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

