// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package com.xforceplus.ultraman.oqsengine.sdk;

public interface SelectByConditionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SelectByCondition)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.EntityUp entity = 1;</code>
   */
  boolean hasEntity();
  /**
   * <code>.EntityUp entity = 1;</code>
   */
  com.xforceplus.ultraman.oqsengine.sdk.EntityUp getEntity();
  /**
   * <code>.EntityUp entity = 1;</code>
   */
  com.xforceplus.ultraman.oqsengine.sdk.EntityUpOrBuilder getEntityOrBuilder();

  /**
   * <code>int32 pageNo = 2;</code>
   */
  int getPageNo();

  /**
   * <code>int32 pageSize = 3;</code>
   */
  int getPageSize();

  /**
   * <code>.ConditionsUp conditions = 4;</code>
   */
  boolean hasConditions();
  /**
   * <code>.ConditionsUp conditions = 4;</code>
   */
  com.xforceplus.ultraman.oqsengine.sdk.ConditionsUp getConditions();
  /**
   * <code>.ConditionsUp conditions = 4;</code>
   */
  com.xforceplus.ultraman.oqsengine.sdk.ConditionsUpOrBuilder getConditionsOrBuilder();

  /**
   * <code>repeated .FieldSortUp sort = 5;</code>
   */
  java.util.List<com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp> 
      getSortList();
  /**
   * <code>repeated .FieldSortUp sort = 5;</code>
   */
  com.xforceplus.ultraman.oqsengine.sdk.FieldSortUp getSort(int index);
  /**
   * <code>repeated .FieldSortUp sort = 5;</code>
   */
  int getSortCount();
  /**
   * <code>repeated .FieldSortUp sort = 5;</code>
   */
  java.util.List<? extends com.xforceplus.ultraman.oqsengine.sdk.FieldSortUpOrBuilder> 
      getSortOrBuilderList();
  /**
   * <code>repeated .FieldSortUp sort = 5;</code>
   */
  com.xforceplus.ultraman.oqsengine.sdk.FieldSortUpOrBuilder getSortOrBuilder(
      int index);
}
